### ISSUE TITLE
Some versions of testing release are skipped on Firefox

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#1063]
I've observed that sometimes Firefox has a newer version of Yomichan on stable release. (auto-update is on)
Some versions seem to be skipped on tesing release, for example the 20.11.1.0 ver this month, I recall this happening a few times in the past months too.
I wonder what may have caused this as things seem to be working normally on the Chrome side.

**Comment by toasted-nutbread** [comment]
Probably because FooSoft forgot to upload it or something. The Firefox testing release is treated differently from the Chrome version, and I don't think patch releases are always uploaded to the testing releases either (maybe they should be). At some point, I'm going to try to simplify the workflow for uploading Firefox testing releases, and make it support automatic updates also, but we aren't there yet.

**Comment by toasted-nutbread** [comment]
New release checklist is being used starting with 21.1.31.0, which should better cover testing release updates.
