### ISSUE TITLE
i dislike the blue

### ISSUE THREAD

**Issue by MrD0lph** [FooSoft/yomichan#1142]
(Describe the feature or change)

**Comment by toasted-nutbread** [comment]
Noted; the blue text is a bug, and some alternatives to the blue bar selection indicator have been implemented and will be queued for a patch release.

**Comment by Thermospore** [comment]
That text coloring is intentional in `Group related terms` mode, right? I find it quite useful there
![image](https://user-images.githubusercontent.com/35350819/102709247-106a7e00-4255-11eb-95a1-bc7a19bed860.png)
(and personally I like it in `Group term-reading` pairs mode too 🤷 )

As for the blue `Current entry` bar, it grew on me pretty quick. I think it looks sleeker than the gold star. The transition animations look nice

The new transport controls look nice. Though, they are now on the opposite side of where you would usually click on a kanji, but that's nbd
![image](https://user-images.githubusercontent.com/35350819/102709212-b5d12200-4254-11eb-9d1b-eb6e9d4a1bb1.png)
(I know there is a kb shortcut to go back, but Language Learning with Netflix steals focus from yomichan so you have to use the mouse)

**Comment by Thermospore** [comment]
Oh sweet, I see the transport position is already addressed here https://github.com/FooSoft/yomichan/issues/1079#issuecomment-748549527

**Comment by tvvoty** [comment]
Yeah, blue clashes a lot against black background, wish it was possible to disable it or at least change the color.

**Comment by toasted-nutbread** [comment]
An update is coming soon to fix that issue; the blue color has been updated to have better contrast against the dark background. Also, the text color should be reverted back to the white color for certain display modes.

Left: old; Right: new
![image](https://user-images.githubusercontent.com/11037431/102734556-1ec8a080-430e-11eb-87d7-df65f0966bbe.png)
