### ISSUE TITLE
"potential or passive" is wrong for Godan verbs ending in る

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#118]
Ichidan Verbs (correct case):
Ichidan verbs can be either potential or passive with the られる suffix. This is shown correctly.
For example: 止められる

-----
Godan Verbs ending in る (bug case):
Godan verbs ending in る conjugate to られる for passive, but they conjugate to れる for potential. This is shown incorrectly as "potential or passive".
For example: 怒られる

-----
There seem to be other similar bugs. For example, Yomichan says 起こされる is either "passive or causative", but the causative is 起こさせる (which isn't even detected by Yomichan).

**Comment by anonymouse333** [comment]
It's pretty weird that such a major issue has taken so long to be reported.

I just installed RikaiChamp out of curiosity to see how that handled both your examples and it turns out that it has the exact same problems that Yomichan does. Unfortunately, it's too late to check if the problem also existed in Rikaisama.

Hope both these issues are fixed in a timely manner. They're pretty serious errors which undermine the most basic purpose of the add-on (especially the latter error which, nevermind telling you the wrong conjugation, completely prevents the look-up of the word in question).

**Comment by seanblue** [comment]
I wonder if they both use another library for that part. I can't imagine every extension builds it's own ability to scan for Japanese and handle conjugations, so that wouldn't surprise me.

**Comment by seanblue** [comment]
@FooSoft Are you going to have a look at this issue? It's a pretty glaring problem.
