### ISSUE TITLE
Update JapanesePod101 audio source

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#122]
It looks like JapanesePod101 recently changed their audio. The speakers are all different and they seem to cover _a lot_ fewer words. If possible, getting the previous audio back would be best. If that's not publicly available anymore, at least updating the primary JapanesePod101 audio source to grab the new audio would be nice. For now, I've had to switch to the backup audio to get the small number of words they still support.

Here is a sample word they still have audio for: 特別.

**Comment by anonymouse333** [comment]
Audio is back again now.

This isn't the first time this has happened. I don't know what the reason is, but at least once before (actually, I feel like it has happened more than once but I'm not 100% certain) JapanesePod101's audio has become unavailable for a while, then suddenly come back again several days or weeks down the line.

**Comment by seanblue** [comment]
@anonymouse333 Thanks for letting me know. It's good to have the previous audio back (for now at least). The new audio was missing a lot of content and had a lot more mistakes.

**Comment by toasted-nutbread** [comment]
Closing this issue as it seems to be resolved. Note that Yomichan now has support for multiple fallback audio sources in case a similar problem occurs in the future.
7ce54864f3fbaaeade2ebc20d80bcb084d9fa426...6208d6c93b3921ac8726140869ae71d784569b48
