### ISSUE TITLE
[Feature Request] Removing dictionary from Anki definitionTags

### ISSUE THREAD

**Issue by byjtje** [FooSoft/yomichan#1229]
When using the Anki feature, despite not being a definitionTag, the dictionary gets added to the first definitionTag of each dictionary defintion, making it more cluttered and adding nothing of value.
If someone wanted to still use it for some reason, they could use `{{~dictionary~}}` in the handlebars or even the `{dictionary}` field

**Comment by toasted-nutbread** [comment]
The underlying data structure of the `definitionTags` array has been updated to omit the dictionary tag. However, instead of modifying the `{glossary}` tag to omit the dictionary tag, I have added a new `{glossary-no-dictionary}` marker which functions the same as `{glossary}`, except it omits the dictionary tag. This maintains backwards compatibility, as there are some cases which having the dictionary may be useful for certain users.

**Comment by byjtje** [comment]
Thank you very much!
