### ISSUE TITLE
[Feature Request] Show entries that match the selected expression plus wildcards

### ISSUE THREAD

**Issue by rgamici** [FooSoft/yomichan#128]
When I add word to Anki, I usually also add some related words, as they help grasp the distinction between synonyms, and also to help reinforce that new word in other possible uses.
For example, on Jisho I can add the wildcards '*' before and/or after the word I'm looking for and it will return other expressions that use that (sub)word.

Is it feasible to add this feature on yomichan?
For example, show those 'similar' result on the list of the results.

**Comment by toasted-nutbread** [comment]
Looking into this a bit while working on #270, it does seem that this is partially possible.

For suffix wildcards, this is possible by making clever use of how strings are sorted. The following can be done using [```IDBKeyRange.bound```](https://developer.mozilla.org/en-US/docs/Web/API/IDBKeyRange/bound):
```js
const term = 'あ'; // example
const query = IDBKeyRange.bound(term, `${term}\uffff`, true, false);
```
Using this query will find all terms beginning with ```'あ'``` (non-inclusive in this case).

The same cannot be done for prefix wildcards due to how strings are sorted. However, it would potentially be possible if each dictionary entry also stored a string reversed version of the search term. This would require re-importing all dictionaries, and the database size would be slightly larger.

The other factor in supporting wildcards is how to show them. Wildcards on the search page could be fairly straight forward: perform no deinflection and only search for terms starting with the exact text before the wildcard. In the popup, wildcards are not as clear-cut with regards to how they could be handled. They should be off by default, but I'm not sure what the best way to incorporate the feature would be, or if it would even make sense to include it.

**Comment by rgamici** [comment]
Thank you for taking my request in consideration.

> The same cannot be done for prefix wildcards due to how strings are sorted.

I'm not sure how useful is to have the prefix wildcard compared to the suffix one, but I would guess at least 30 % of the total.
Since I've never experienced yomichan reach the limits of available memory both on HDD or RAM, I think a *slightly* increase would be imperceptible.
Do you have an approximate estimation of how bigger it would be considered the current database size?

If the bottleneck is the time necessary to process the request, maybe another modifier key could be used to activate the wildcard search.
For example, currently the `shift` key is used to search a word, and then `ctrl+shift` could be used to do the wildcard search.
I'm not sure how easy it would be to add this, but it would leave normal users unaffected.

I've currently installed the dictionaries JMDict, KireiCake, and JMnedict.
The first two sometimes miss an entry or have them split, and having both usually gets a slightly better result than have only one of them.
The last one I hardly use, but it still appear for any word I search.
It is not always that I need to scroll down the list, because usually the first result is enough.
But, when it is not, I have to search for the word manually on `jisho.org` to get a better idea of what it means, or even a more slow search for the word in use on sentences to infer the meaning.

For example, searching the word `摂取`, I get the following results:
* 摂取 - JMdict (English) - Part of the entry (3 definitions) - intake; absorption; adoption
* 摂取 - JMdict (English) - Part of the entry (1 definitions) - assimilation
* 摂取 - KireiCake - (4 definitions, the same as combining the ones from JMdict)
* 摂 - JMnedict - each one for a different name
* 摂 - JMnedict
* 摂 - JMnedict
* 摂 - JMnedict
* 摂 - JMnedict

From `jisho.org` when I search for `*摂取*`, I get:
* 摂取
* 過剰摂取
* 摂取量
* 耐容１日摂取量

The definition of the first one is slightly better than the one I get from yomichan, because they are longer and provide more details.
The extra results make the meaning and use of the word clearer, and it is enough to understand when the word is used and when it is not.
Having yomichan include the wildcard search would make it faster to understand, and also avoid forcing and user to break the reading rhythm to open an external dictionary search.

> In the popup, wildcards are not as clear-cut with regards to how they could be handled. They should be off by default, but I'm not sure what the best way to incorporate the feature would be, or if it would even make sense to include it.

I think that having it show the exact match, and then words with wildcard ordered by their length (and eventually repeating it for other dictionaries with lower priority) seems to work for me.
It is not perfect, but I think it does a good job as usually the longer the word more sub-words it has, including some other results matched by the wildcards, and it is also more specific and less useful.

I think that labeling it as a deeper search could be a good way to inform the users of what is it for.
The default search is enough most of times, but when it fails, there is still a tool available before having to do a search outside for sentences using that word to try to get the meaning.

I'm not sure about other users, but as I increased the number of words I have on Anki, I only need to search for words that are too specific and also too rare to encounter again to help me memorize them.
I think most users get the same problem, and as I mentioned in the previous message, the redundancy helps to be more exposed to the word and makes it easier to memorize them.
Since yomichan already supports an Anki integration, it is also another useful tool for users who use both.

**Comment by toasted-nutbread** [comment]
#274 adds support for suffix wildcards on the search page. I'll see if I can look into some ways to best present additional information on the popup without it becoming too cluttered/long. I think that it may need to be a non-automatic process (e.g. clicking a button/link), since the lookups can be non-trivially long. For example, ```あ*``` returns all words beginning with ```あ```, which we would typically not care about by default. So time is definitely partially a concern there.

> I think a slightly increase would be imperceptible.

This is likely true, but it will take some profiling to verify. Another case to consider is that desktop browsers are more efficient at storing database information than mobile browsers. Firefox Mobile databases take up ~3x more storage space than then desktop counterpart, and mobile devices are much more likely to run into storage issues.
