### ISSUE TITLE
"Group results by main dictionary entry" causes error on word lookup

### ISSUE THREAD

**Issue by zacharied** [FooSoft/yomichan#130]
As described in the title.

For example, this works fine.

![image](https://user-images.githubusercontent.com/6374275/43371872-1c8cb0de-9368-11e8-86fe-275d4346db9f.png)

However, when I mouse over the 心, I receive this error:

![image](https://user-images.githubusercontent.com/6374275/43371895-5f4ecd94-9368-11e8-8dc0-7991259e29c2.png)

Is anyone able to reproduce this?

**Comment by siikamiika** [comment]
It probably has something to do with your 研究社 dictionary, but I don't have a copy to test it. It could have an empty tag for some definition of 心. Relevant lines in code:
https://github.com/FooSoft/yomichan/blob/7cfcfb3bf34bb128dc4f5a47e7846fe4cc4c8c81/ext/bg/js/translator.js#L58-L163
...that calls
https://github.com/FooSoft/yomichan/blob/7cfcfb3bf34bb128dc4f5a47e7846fe4cc4c8c81/ext/bg/js/translator.js#L299-L316
Making line 303 safer and skipping the name instead of calling its `split` method could be one solution, but fixing the issue in Yomichan Import would be better.

**Comment by toasted-nutbread** [comment]
Closing as I think this issue is resolved. I tested the sentence you had listed with kenkyuusha installed and didn't encounter any error.
