### ISSUE TITLE
Audio not downloading mp3 into cards

### ISSUE THREAD

**Issue by zero57** [FooSoft/yomichan#137]
Testing on Arch Linux 64 bit, both Firefox 61 and Chromium 68 with Anki 2.1.2 and AnkiConnect v.6, it seems like when trying to populate the card with the `{audio}` tag, it doesn't download the mp3 and insert it in the card anymore. I have the audio source set to JapanesePod101, and I've also tried other audio sources, but it still doesn't work.

Trying to add a card with audio on a word like: 日本
Has audio playing when clicking the speaker icon on JapanesePod101 audio source, but doesn't insert it into the card when having a card's audio field value set to `{audio}`

**Comment by blhorii** [comment]
I've been experiencing the same problem since updating to Anki 2.1.  I've experienced with Anki 2.1.2, 2.1.3, and 2.1.4.  I'm using macOS High Sierra v10.13.6 and Chrome Version 68.0.3440.106.  When I go back to Anki 2.0.52, the problem goes away.  I've tried re-installing Anki and re-adding AnkiConnect, but reverting to the old version of Anki is the only solution I've found.

**Comment by toasted-nutbread** [comment]
Closing as out-of-date and likely fixed. Please open a new issue if the problem persists.
