### ISSUE TITLE
[Feature Request] Integration with 3rd party Audio TTS service (I can implement)

### ISSUE THREAD

**Issue by lucwastiaux** [FooSoft/yomichan#1386]
I'm the maintainer of the Anki AwesomeTTS addon (and also developer of a new addon called Language Tools which also does text to speech for Anki). These addons have required development of a (paid) REST API which is a unification layer (which I call "Cloud Language Tools") around paid TTS services (Google Cloud, Azure, Watson, Amazon AWS, Naver). This includes 21 high quality Japanese voices. And now, some of my fans on patreon are asking me whether that service can be integrated with Yomichan. I understand there is a custom audio setting which could be used for this purpose. But would Yomichan developers be open to a deeper integration ? I would do the development and testing. 

Some more information about AwesomeTTS: https://ankiweb.net/shared/info/1436550454 , and Language Tools: https://ankiweb.net/shared/info/771677663

A zip file containing the sound samples can be downloaded here: https://cloud-language-tools-samples.nyc3.digitaloceanspaces.com/awesometts_languagetools_voice_samples.zip

**Comment by toasted-nutbread** [comment]
I suppose it depends on what the expected workflow for the user is and how the custom audio would be used. That is, would it be used for playing audio for terms in isolation, or something more broad like TTS for sentences?

1. The first is supported by the use of a custom audio URL. This allows either one or multiple audios clips to be returned for each term. There are some current limitations for creating cards when multiple audio clips are available, but those can be potentially addressed.

   Fetching from a more complex custom service such as the one you described can currently be done by using a (localhost) middleware server that runs in the background and handles Yomichan's requests and converts them to the expected REST format (set headers, cookies, API keys, other info, etc.). Since it seems your workflow is intended for use with Anki, you could potentially do this as an Anki plugin, similar to the way AnkiConnect works.

   For reference, this is the schema describing the JSON data format that a server returning multiple audio sources would return:
   [custom-audio-list-schema.json](https://github.com/FooSoft/yomichan/blob/2b4af57bd764ee07ed1d7db8e2985e34ba7ef8ea/ext/data/schemas/custom-audio-list-schema.json)

2. The second is not currently supported but could potentially be done depending on what's necessary.

**Comment by lucwastiaux** [comment]
Looks like the current capabilities are sufficient to implement what I want, thanks fro the advice !

**Comment by lucwastiaux** [comment]
I've released the feature, more details here: https://www.patreon.com/posts/48444705
