### ISSUE TITLE
Readings

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#1408]
With that new update I can't find how to enable readings near kanji in a popup, just like here
![chrome_pikJIQ8k2W](https://user-images.githubusercontent.com/24941285/108065707-731ea100-706f-11eb-9ff4-15eb9cd947d8.jpg)
Is there an option for it?

**Comment by toasted-nutbread** [comment]
Not exactly a bug, but more of an oversight: this seems to have been broken for modes other than merged mode. This is due to some layout changes, and the search tags weren't added to this location. I'll fix this.

**Comment by toasted-nutbread** [comment]
Re-opening to pose a question:

Would it be more helpful to your use-case if the expression and reading were displayed separately, rather than using <ruby>furigana<rt>ruby tags</rt></ruby>?

I.e instead of:
### **<ruby>走<rt>はし</rt></ruby>る** [tags...] [走る] [はしる]

The following:
### **走る はしる** [tags...]

**Comment by toasted-nutbread** [comment]
FYI: added an option _Term display style_ to display readings next to terms.
