### ISSUE TITLE
Audio autoplay: The audio for this clip is currently not available

### ISSUE THREAD

**Issue by weirdalsuperfan** [FooSoft/yomichan#1420]
**Description**
"The audio for this clip is currently not available. It will be recorded and uploaded shortly. Thank you for your patience."

Ever since yomichan updated for me this week, I've been getting this annoying audio message multiple times in a row basically every time I hover over anything. This never used to happen before. I'm not sure what my previous version was, since I rarely close my browser, but last time I checked I still had the old settings UI - I haven't even begun to try to understand the new one; it just showed up someday this week or last.

I know that the message itself is from whatever audio service yomichan uses, because I've gotten it before through yomichan, but never like this. I'll even get it multiple times at once, creating an echo. It's made yomichan all but unusable for me. I use the sound autoplay feature right now btw, if you couldn't tell. I suppose I could try disabling that and linking it to a shortcut instead, but obviously that's not a permanent solution. Anyway, yomichan makes my life a living hell at the moment.

**Browser version**
Chrome Version 86.0.4240.75 (Official Build) (64-bit)

**Yomichan version**
21.1.31.1

**Exported settings file**
[yomichan-settings-2021-02-18-18-07-11.txt](https://github.com/FooSoft/yomichan/files/6004902/yomichan-settings-2021-02-18-18-07-11.txt)

**Comment by toasted-nutbread** [comment]
You are using a custom audio source as your top entry, `http://assets.languagepod101.com/dictionary/japanese/audiomp3.php?kanji={expression}&kana={reading}`, which is the same as the `JapanesePod101` source. Switch to that source instead and it should work.

Some of the logic was changed, and the source is also factored into "invalid" audio. So since the source is `custom` instead of `jpod101`, the invalid check isn't triggered.

**Comment by weirdalsuperfan** [comment]
THANK YOU! Making that change fixed it.

Glad I uploaded the settings file.
