### ISSUE TITLE
Yomichan does not work on Google News

### ISSUE THREAD

**Issue by snthibaud** [FooSoft/yomichan#143]
I tried visiting news.google.com and noticed that Yomichan does not display any definitions on this page. On Yahoo news it does work, however. Any idea what might be wrong. I am using Firefox 62.0.3.

**Comment by siikamiika** [comment]
I was able to reproduce this issue on Firefox 68. It appears to be caused by an absolutely positioned a tag sitting on top of each article container like this:
![2019-07-29_03-30-35](https://user-images.githubusercontent.com/5602483/62015333-4e27bc00-b1b3-11e9-85a4-af3af1d4c8cc.png)

When I remove the `position: absolute`, I'm able to use Yomichan again.

To make this permanent (until Google changes their site again), it seems to be possible to hide the entire link with this rule in your uBlock Origin custom filters:
```
news.google.com##:xpath(/html/body/c-wiz/div/div[2]/div[2]/div/main/c-wiz/div[1]/div/div/article/a)
```

Unfortunately I don't know how to fix this issue in a general way in Yomichan.
