### ISSUE TITLE
Highlighting not working on Firefox when CSS has `user-select: all`

### ISSUE THREAD

**Issue by doubutunomorai** [FooSoft/yomichan#1435]
Description
go to any page with text that has CSS user-select: all e.g. https://jsfiddle.net/tLm2sx0v/
hover over it (using modifier key if you have one enabled)
nothing happens
works on chrome, only broken on firefox
 
Browser version
Firefox 85.0.2
 
Yomichan version
Yomichan 21.1.31.1

**Comment by toasted-nutbread** [comment]
Nice find, fixed in #1436. Looks like Firefox's [`caretPositionFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/caretPositionFromPoint) behaves differently than the API Chrome uses ([`caretRangeFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint)).
