### ISSUE TITLE
Characters dublicating themselfes

### ISSUE THREAD

**Issue by aantsu3** [FooSoft/yomichan#1476]
(In Yomichan Search) When I type any japanese characters and press enter, they just duplicate themselfes.
![Снимок экрана (1601)](https://user-images.githubusercontent.com/77245268/109698302-182d9380-7bb1-11eb-92c8-f0bd909994c6.png)
![Снимок экрана (1602)](https://user-images.githubusercontent.com/77245268/109698313-1a8fed80-7bb1-11eb-97b3-45f5c3f06ea1.png)

**Comment by toasted-nutbread** [comment]
It appears to be an issue with IME text input. I'll try to include the fix in the upcoming stable release, but as a temporary workaround, you can use Shift+Enter instead of Enter when selecting an IME completion to avoid the bug.

**Comment by Thermospore** [comment]
I have the same issue on Chrome + Google 日本語入力 IME. It only happens if I tap enter twice very quickly though (out of habit, since on most sites/programs the enter key isn't accepted when you are in the 変換)

so the "workaround" for me is to just tap enter once (which simultaneously closes the 変換 and executes the search)

huh now that I look closely, even when just tapping enter once you can see the double text flash for a frame or so

Nice to have this looked at!
