### ISSUE TITLE
Yomichan ceased functioning

### ISSUE THREAD

**Issue by sigmareaver** [FooSoft/yomichan#1517]
**Description**
Unfortunately I have no idea how/why/when this happened. Does Yomichan force updates or something? I usually have auto-updates turned off whenever possible.

I went to turn Yomichan on to do some reading, and discovered it wasn't working. When I flip the on/off switch to on, it ends up back in the off position. Similarly, the other buttons on the widget were non-responsive. I had to go to the add-ons page to access the Yomichan options page.

Similarly, on the Yomichan options page, nothing was responsive. My dictionaries were gone. My settings were gone. Notably, the settings page was different, and had a warning at the top with a link referring to this Github repository. This leads me to my assumption that Yomichan is silently forcing updates.

This kind of thing is unwelcome. Please ask people if they want to update. At this point, I am forced to stop using Yomichan, because a) I don't even remember what dictionaries I was using, and b) I don't agree to forced updates.

**Browser version**
Firefox 66.0.3

**Yomichan version**
Couldn't say. I was forced to uninstall the add-on.

**Exported settings file**
Export button, like all other UI elements, was non-functional.

**Comment by toasted-nutbread** [comment]
> Unfortunately I have no idea how/why/when this happened. Does Yomichan force updates or something? I usually have auto-updates turned off whenever possible.

Yomichan doesn't force it updates, it's a browser-level option as far as I am aware.

Likely the same issue as #1510. There was a compatibility issue with a feature which wasn't present in older version of Firefox, and it was causing an error on startup. If you haven't uninstalled, the update will fix everything and no settings/dictionaries will be lost. Otherwise, the latest version that went out last night fixes this issue.
