### ISSUE TITLE
[Feature Request] Resolving alternate forms of words

### ISSUE THREAD

**Issue by sihue** [FooSoft/yomichan#1546]
I'm not quite sure how feasible this is, but it would be nice to have a more robust mechanism to resolve alternate forms of words independent of the used dictionary.
As it stands, it can be quite easy to miss the most relevant entry, especially when kana are involved.
Two quick examples for this, first the actual occurance, then the most relevant (missed) entry in the dictionaries I'm using:

雄たけび　　雄叫び
引っかかる　引っ掛かる

Jisho.org recognizes them, but then again, it simply has the alternate forms baked into the dictionary.
The question I'm having is this:
Would it be possible to compile alternate forms from an expansive open source dictionary and then search for all forms in the personally selected dictionaries?
E.g.  雄たけび → 雄叫び 【おたけび】、雄たけび 【おたけび】、雄叫び 【おさけび】 → 雄叫び.

(Another conceivable alternative would be to "guess" (recognized/official) readings. E.g. 雄たけび → おたけび → 雄叫び. On the surface, this seems rather error prone, though.)

Best regards.

**Comment by toasted-nutbread** [comment]
You can kind of do this using merged mode on dictionaries that support it, but ultimately it's a formatting issue with the dictionary if it doesn't include the right info.

![image](https://user-images.githubusercontent.com/11037431/111891998-9e2d4500-89cd-11eb-9be0-40ad2d687e78.png)

**Comment by Thermospore** [comment]
Off topic, but that screenshot reminds me. I ripped the KireiCake data directly from the site and formatted it for yomichan, so everyone can be free from old jmdict :^)

[RikaiCake [upper table] v1.zip](https://github.com/FooSoft/yomichan/files/6177362/RikaiCake.upper.table.v1.zip)
[RikaiCake [lower table] v4.zip](https://github.com/FooSoft/yomichan/files/6177361/RikaiCake.lower.table.v4.zip)

Feel free to do whatever with 'em! Lower table didn't include PoS info. Upper table included PoS info, which I imported. I used a google sheet to build each of them, and put a link in the metadata. (upper table was a huge pain btw. Weird/inconsistent formatting and many one-off errors)

Although the truth is, the more time I spent looking at the definitions the more I realized... they kinda suck. At this point I just have them installed because I feel obligated to watch out for errors

**Comment by sihue** [comment]
(I have to admit, I couldn't find merged mode with a quick search on the settings page.)

I guess my thinking was that resolving alternate forms of words is similar to deinflection of verbs, which is done on yomichans end. But unlike with deinflection, you can't really fit the required data for alternate forms in ~1000 lines. So, if you don't feel like exploring this idea further, you can close the issue.

**Comment by Thermospore** [comment]
> (I have to admit, I couldn't find merged mode with a quick search on the settings page.)

this bad boy
![image](https://user-images.githubusercontent.com/35350819/111907390-f124ed80-8a09-11eb-9b83-1af1fb5fd903.png)

I assume you are using jmdict, that's what jisho uses too. When you use merged mode all of those alternate forms will be in one entry in yomichan, and your life will be great
![image](https://user-images.githubusercontent.com/35350819/111907617-00f10180-8a0b-11eb-9c97-d8d2ef5b32d4.png)

jmdict generally puts the most common form first (the main form you see in jisho). things are still very much actively being worked on though. I like to build a new copy every month or so using yomichan import. Whenever I see a form they don't have I go on their database and submit it so other people can find the entry more easily (don't worry, all edits must be approved by one of the moderators)

This is also incredibly handy for pulling up jj dicts, as they are much less flexible with their forms. for example 新明解 only has 色色, but even if I search 色々 it comes up because they are both in jmdict and I have all my jj dicts set as a secondary search dictionary of jmdict. you can see that setting in my above screenshot
![image](https://user-images.githubusercontent.com/35350819/111907960-4104b400-8a0c-11eb-9960-56e0b1900bd6.png)

**Comment by toasted-nutbread** [comment]
> I guess my thinking was that resolving alternate forms of words is similar to deinflection of verbs, which is done on yomichans end. 

There's not really a good way of knowing this in general without having many special cases for specific verbs. Hence why the dictionaries support this information for multi-term entries.

Otherwise, check @Thermospore's comments, he covered it pretty well. (I keep referring to that mode as "merged" mode since that's the old/internal name for it; maybe I should update that.)

**Comment by sihue** [comment]
Thank you both for the comprehensive explanation.
I like to keep the popup window as free from English as possible, plus I'm not a huge fan of the tag flood introduced by JMdict, so I won't be using it for now. It is nice to know that it's possible, though. Since my request, by any reasonable metric, is already pretty much covered, I'll be closing the issue. Maybe in the far off future we'll have a Japanese localization of yomichan for the ultimate monolingual experience. ;)

**Comment by toasted-nutbread** [comment]
> I like to keep the popup window as free from English as possible, plus I'm not a huge fan of the tag flood introduced by JMdict, so I won't be using it for now.

That's an understandable use case that I'm sure more than a few users have. I don't know what dictionaries you are using, but depending on what their origin is, they could have related term information added. That would likely be more of a task that falls in the category of this project: https://github.com/FooSoft/yomichan-import

> Maybe in the far off future we'll have a Japanese localization of yomichan for the ultimate monolingual experience. ;)

Internationalization beyond just English would be a nice feature to have, but it would likely require volunteers to support translation into different languages.

**Comment by Thermospore** [comment]
> I like to keep the popup window as free from English as possible

Yeah Ive been wondering what I'll do about this, once I'm at the point where I'll hide all English definitions for good (probably soon). Was thinking I could edit the jmdict xml to remove the English definition text and reimport it.

Or perhaps there could be an option to hide/collapse a dictionary's definitions, so you can use it solely for the related term info. Jmdict really is a great database for that sort of thing already, especially because it is very easy to submit anything new you find

**Comment by sihue** [comment]
> Internationalization beyond just English would be a nice feature to have, but it would likely require volunteers to support translation into different languages.

Crowd sourcing the translation of a couple hundred strings probably wouldn't even be that difficult, but maintenance/synchronous updates seem like a nightmare.

> Or perhaps there could be an option to hide/collapse a dictionary's definitions, so you can use it solely for the related term info.

This is sort of what I had in mind initially. Let yomichan work internally as though a dictionary was installed and then simply hide its results. From a developer's perspective it may seem like a bit of a hack, though.

> That's an understandable use case that I'm sure more than a few users have.

I may have jumped the gun here.
I'll reopen the issue. Just don't feel any obligation to rush changes.

**Comment by toasted-nutbread** [comment]
> Crowd sourcing the translation of a couple hundred strings probably wouldn't even be that difficult, but maintenance/synchronous updates seem like a nightmare.

It's probably in the range of 1000-2000 at this point. It would take a bit of work to prepare for that, so at the very least, that goal is a little far off.

> This is sort of what I had in mind initially. Let yomichan work internally as though a dictionary was installed and then simply hide its results. From a developer's perspective it may seem like a bit of a hack, though.

The collapsing thing has also been kind of requested in #1051, so it's on the radar at least.
