### ISSUE TITLE
Anyway to prevent this mild annoyance? (sentence import)

### ISSUE THREAD

**Issue by Aakasan** [FooSoft/yomichan#158]
The way I study is to keep an open HTML tab w/ Clipboard insert add  on. So whenever I find an interesting sentence I'd want to sentence mine- it would directly appear there.

[https://prnt.sc/mt0n6f](This is a rough example of how it ends up looking). Just copied a bunch of random words into the html file.

[https://prnt.sc/mt0lft](url)  I select which word's definition I want along with the sentence line. 
Ideally, I just want the single line "長風呂" 
[https://prnt.sc/mt0kzc](But this happens) It copies everything below (marked blue)  as well. It's a bit of a minor annoyance as I have to edit them out while reviewing.

Anyway to prevent this? I'm pretty sure it's not a problem with yomichan. Likely something with the html file but I have no idea about how to fix it. Would appreciate any assistance.

**Comment by psychodelicwasabi** [comment]
In the <b>Settings</b> you can choose the limit of the sentence's length in characters, if you make that to be 3~4, you'll likely have less trouble with it. You can also erase the value for the sentence field in the importing options. In both cases you'll limit your sentence import and maybe have to do that manually if you're interested in sentence mining, but since you just seem to be mining words, that may not be a problem.

**Comment by psychodelicwasabi** [comment]
In the Settings you can choose the limit of the sentence's length in characters, if you make that to be 3~4, you're likely to have less trouble with it. You can also erase the value for the sentence field in the importing options. In both cases you'll limit your sentence import and may have to do that manually if you become interested in sentence mining, but since you just seem to be mining words, that may not be a problem.

**Comment by siikamiika** [comment]
Sentences are delimited by periods (. 。), so if you add a one to the end, the sentence should be cut from there.

**Comment by Aakasan** [comment]
Is there a way to edit a blank html file to add a period at the end of each
new text copied from the clipboard inserter?

**Comment by siikamiika** [comment]
You can run this script in the console:
```js
setInterval(() => {
  document.querySelectorAll('p').forEach((p) => {
    if (p.innerText.slice(-1) != '.') {
      p.innerText = p.innerText + '.';
    }
  });
},1000);
```
Every second, it checks every paragraph on the page and if they don't end in a period, one will be added. It's a dirty hack and you should really request a feature for [clipboard inserter](https://github.com/kmltml/clipboard-inserter) instead.

**Comment by Aakasan** [comment]
Thank you so much.  I added the script to my html file and it's working
great.
I'll request the feature for clipboard inserter as well.
