### ISSUE TITLE
Tags appearing on hover when there's one word

### ISSUE THREAD

**Issue by Aridow** [FooSoft/yomichan#1581]
**Description**
I don't know if it's a bug or not. When in "group related terms" mode, some tags appears on hover. I think this shouldn't be the case when there's only one word. Same with popular words appearing blue, I think this isn't necessary when there's only one word.

**Browser version**
Firefox 87.0

**Yomichan version**
21.2.28.2

**Exported settings file**
![image](https://user-images.githubusercontent.com/65539338/113358821-cb231580-9346-11eb-9a69-78ac037910ce.png)

**Comment by toasted-nutbread** [comment]
It is expected, albeit perhaps confusing or unnecessary. The tags appearing below the headwords is a somewhat new addition, where the intent is to make it more consistent with the other display modes. I left the show-tags-on-hover functionality in for now, but I would like to get rid of them in favor of a better option in the long-term; it's an accessibility issue on touchscreen devices.

There's a similar issue with the audio button requiring a hover, which was briefly discussed a while ago as well. The resolution was to leave the audio buttons as only appearing on mouse hover, even for entries with a single headword, but this is still an accessibility concern.

**Comment by Aridow** [comment]
If the point is to have the two systems at the same time, I think all the tags that can be seen on hover, should also be seen below the word. In my screenshot, the kanji and reading tags aren't, and since I use them for copy-paste or scan, it would be more convenient.

**Comment by toasted-nutbread** [comment]
There are two systems currently because the mouse-hover system is in the process of being phased out, but I am hesitant to make that entire change all at once, as some users may rely on it.

The reason the term/reading tags aren't also on the lower line is because certain terms have many spelling variations, which adds a lot of tags. It also makes it harder to correlate which term/reading goes to which headword. So I'm working out how to best present the information that works for all situations.

**Comment by Aridow** [comment]
> The reason the term/reading tags aren't also on the lower line is because certain terms have many spelling variations
I understand, but that's why I was talking about "when there's only one word" (and only one reading), like on my screenshot.
