### ISSUE TITLE
[question] purpose of splitting up term bank?

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#1738]
I notice most dictionaries split up their term banks into multiple files. What is the purpose of this?

I just made a fairly large freq list (about 850k entries (lol)) and it seems to work fine with the term bank in a single file, afaict
[wikipedia_freq_v2.zip](https://github.com/FooSoft/yomichan/files/6649461/wikipedia_freq_v2.zip)

thanks :^)

**Comment by toasted-nutbread** [comment]
To be honest, I don't think there is a reason anymore. I don't think it affects the end results after importing, but it may provide a slight optimization during the import process, or at least it used to. I think the progress bar used to be tied to the # of files rather than the # of entries in the files, but that's since been changed.

**Comment by Thermospore** [comment]
Interesting, thanks

**Comment by FooSoft** [comment]
The original purpose here was to provide progress during import and prevent the extension from being killed by Chrome for becoming unresponsive for a long time (while doing the IndexedDB import). Don't know if this is required anymore.

**Comment by toasted-nutbread** [comment]
Yep, that sounds about right. For reference, the data is currently segmented into chunks of 1000 for each transaction, so even if files aren't segmented, they should still load.

https://github.com/FooSoft/yomichan/blob/0556c503195fb274069817514ceaad9ed2f1c998/ext/js/language/dictionary-importer.js#L182-L200
