### ISSUE TITLE
Audio Sources: Text-to-speech Voices in Firefox on Linux is not displaying useful voices

### ISSUE THREAD

**Issue by zignd** [FooSoft/yomichan#1740]
I'm not really sure if this is a bug, but I have both Chrome and Firefox on my Linux machine (running Ubuntu 20.10) and when I check the Audio Sources settings dialog on Firefox and look for a text-to-speech voice to use, there are only options that can't read Japanese in a useful manner. They all sound very robotic and impossible to understand.

Is it something that only happens on Firefox on Linux? Those text-to-speech voices are browser dependent? I mean, Yomichan on Chrome display voice options that seems to be from Google Translate, which sound nice. Do you guys have any suggestion for me?

Here's a screenshot of what shows up for me. Also, this list is extreeeeemly huge and full of duplicate entries, I wonder if this is a bug. When I try to open the HTML select element the tab freezes for a moment.

![image](https://user-images.githubusercontent.com/3194806/122215645-d4217e80-ce81-11eb-8eda-545438b720a3.png)

**Comment by toasted-nutbread** [comment]
Yomichan is listing all the voices it detects using the [SpeechSynthesis](https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesis) API, and this is browser and OS dependent. Japanese voices are shown at the top of the list, but I'm not sure why your device would list so many. You could test a [SpeechSynthesis demo webpage](https://cdpn.io/3642066/fullpage/rawrYP) to see that it probably also has a gigantic list of voices.

> When I try to open the HTML select element the tab freezes for a moment.

Likely just due to the large amount of items, since it's creating a new window and populating it.

> full of duplicate entries

Could you inspect element on the dropdown and copy its "Outer HTML" and paste it here? I'm curious if it is actual duplicates vs lookalikes.

**Comment by zignd** [comment]
> Yomichan is listing all the voices it detects using the SpeechSynthesis API, and this is browser and OS dependent. Japanese voices are shown at the top of the list, but I'm not sure why your device would list so many. You could test a SpeechSynthesis demo webpage to see that it probably also has a gigantic list of voices.

Interesting, I didn't know about that! I just tried the demo page on Firefox and it also displays a huge list of options (screenshots below), but seems to be the same options as shown on Yomichan for me. But when I try this demo on Chrome it only shows a few normal options as expected, I suppose.

<details>
  <summary>Screenshots</summary>

Firefox:
![image](https://user-images.githubusercontent.com/3194806/122307251-5ccf0780-cee0-11eb-9220-272992257e20.png)

Chrome:
![image](https://user-images.githubusercontent.com/3194806/122307487-d666f580-cee0-11eb-8138-39772c4e39e4.png)
  
</details>

Also, after reading your reply I decided to check on another Linux machine that I have, and there Yomichan displays a small list of voice options on Firefox. There's one that can read Japanese, although it's very robotic. Kinda of unpleasant to hear, but at least sounds like Japanese.

Do you know about any other audio sources that could be added via Custom URL maybe? On Chrome I usually rely on the Google voice because it manages to read most of the words. I tried to look into the Yomichan documentation, but couldn't find example of services providing a public API for text-to-speech that could be used easily on Yomichan.

> Could you inspect element on the dropdown and copy its "Outer HTML" and paste it here? I'm curious if it is actual duplicates vs lookalikes.

Sure, I had to upload it to because the select element was almost 1MB of text. (It's the first time I'm using this upload feature on issue, hope it works). Here's the code: [yomichan-select-element.txt](https://github.com/FooSoft/yomichan/files/6666277/yomichan-select-element.txt)

**Comment by toasted-nutbread** [comment]
> I just tried the demo page on Firefox and it also displays a huge list of options

I suppose it's just an idiosyncrasy of Firefox on Linux or the setup you have, albeit it seems like a poor design decision, since it looks like each voice is given a "variant" for an extremely large number of languages, most of which don't work. Chromium likely implements it differently, in a more sane manner.

And wow, ~10k entries, that's pretty bad, but I don't think there's any way for Yomichan to detect whether any of them are truly "valid".

> Do you know about any other audio sources that could be added via Custom URL maybe?

I am not aware of any that function without additional software (besides one of the JPod variants, which is already supported natively). #544 and #1386 are related and show some of the functionality, AFAIK most users who use it have set up some custom service to provide audio.

**Comment by zignd** [comment]
Yeah, that way too much entries, I probably installed something wrong on this machine. But no problem, I think for now I will continue to use Chrome, due to the Google Translate voice being more friendly to hear. Thanks for your time @toasted-nutbread! I believe I can close the issue
