### ISSUE TITLE
No "Add to Anki" button on Firefox

### ISSUE THREAD

**Issue by jacobalbano** [FooSoft/yomichan#190]
The button to add terms to Anki has suddenly stopped appearing for me. I've tried restarting Firefox, Anki, Yomichan, and even my computer but nothing has caused it to come back.

![image](https://user-images.githubusercontent.com/3813170/63738256-321d4600-c857-11e9-8883-d4655ebec9ca.png)

When I navigate to http://localhost:8765/. I do see the `AnkiConnect v.6` message. Creating a new deck in Anki and then opening Yomichan settings shows the deck in the drop-down:
![image](https://user-images.githubusercontent.com/3813170/63738377-8e806580-c857-11e9-9348-b912d0c50919.png)

I've seen this issue come up for a few people in the Japanese-learning community I'm part of, but I've never had a problem before. I'd like to know if there's any way I can troubleshoot this.

**Comment by siikamiika** [comment]
@jacobalbano Have you edited your Anki templates in the past? The error you're experiencing is probably caused the new feature letting you embed screenshots of the page to your flashcards, because edited templates don't get updated with the new default. If your template is missing screenshot, it will not work (this could probably be fixed somehow but I haven't investigated yet).

To fix the issue, you can either reset your templates to default or add the following there:
```
{{#*inline "screenshot"}}
    <img src="{{definition.screenshotFileName}}" />
{{/inline}}
```

**Comment by jacobalbano** [comment]
@siikamiika That fixed it, thanks. I doubt I'm the only person to have edited the templates though; any chance of a fix that doesn't silently fail when a field is missing? I don't plan to use the screenshot feature and it seems that the template should only be *required* to include fields that you want to capture.

**Comment by FooSoft** [comment]
The settings could be versioned, fixing up this issue in the process... however I imagine that at this point it might be moot since the current vetsion has been out for a little while already.
