### ISSUE TITLE
No longer recognises vertical text

### ISSUE THREAD

**Issue by RandomName132** [FooSoft/yomichan#191]
Since the latest update, it seems Yomichan has been unable to detect any vertical text (even single characters). For example, the text on http://tategaki.github.io/awards2015/

**Comment by siikamiika** [comment]
Are you using Chrome? There is some conditional code in Yomichan because scanning on Firefox had issues with this https://github.com/FooSoft/yomichan/commit/0cc5566886f34f781072c1b0ae9ce85a12295a7e, and some code similar to it is still in effect for Chrome. It would somehow have to be adjusted for vertical text but I'm not sure how to detect it reliably or if it's possible to just check both at once. Any ideas @Garethp @toasted-nutbread ?

**Comment by toasted-nutbread** [comment]
I'm not even sure what the point of the extra y check is in the first place, even as I did some refactoring on that part of the code. Testing the releases from the Firefox and Chrome Addon stores, scanning worked with both.

@RandomName132 Can you share which dictionaries you have installed and what your settings are? (Settings found via Options => "Show advanced options" > "Show debug information" > text blob at the bottom of the page)

**Comment by Garethp** [comment]
I don't remember too well, but I think it was in there because whatever I was using to test RikaiRebuilt had the popup appearing even when the cursor was a row or two below the word. It's been over a year, so I can't remember how to reproduce it. That being said, for RikaiRebuilt it's scanning that vertical text in Firefox even with it in, so I doubt it would be that check that's causing the issue

**Comment by Garethp** [comment]
Sorry, I actually did manage to reproduce the issue that the check fixes on the page you linked. I removed the check for RikaiRebuilt and moved my mouse between the two texts next to each other, but much below the text where the mouse isn't actually moving over any characters. I've attached a screenshot

![Without-Check](https://user-images.githubusercontent.com/709912/63942070-e04a0b00-ca64-11e9-9ddc-c8b985fd8e6a.png)

**Comment by siikamiika** [comment]
@toasted-nutbread I tried scanning the paragraphs (for example the one starting 最終審査会における皆さまのプレゼン) on Chrome, and couldn't. After changing https://github.com/FooSoft/yomichan/blob/cd75f5b97dd47e252854d6381b49d2b7bc77c3ce/ext/fg/js/document.js#L165 to `true` it worked again. The title worked even before that, but the popup would disappear between characters. I think it's related to the font size.

@Garethp I've also had the issue before, but Yomichan shows the popup next to the word it finds instead of the cursor. It's not very noticeable if you use a scanning modifier but with always-on scanning it can be annoying. Would it be possible to keep it enabled at least for Chrome but make it more loose than a few pixels?

Anyway my intuition says that the problem is that the center of the character rectangle is in the beginning (left corner for horizontal and top corner for vertical text) of the character, and on Firefox the first character of the line seems to extend to the previous line. I created an issue about it before but it's not very detailed https://github.com/FooSoft/yomichan/issues/173

**Comment by toasted-nutbread** [comment]
So interestingly, the issue seems to be with how different browsers determine what ```Range.getClientRects()``` returns.

For example, the original reason why the ```IS_FIREFOX``` check was added was to address this discrepancy:

On Firefox, when the mouse pointer is at the location specified (red circle), ```document.caretRangeFromPoint.getClientRects()``` is returning rects at the line above (red bar):
![image](https://user-images.githubusercontent.com/11037431/63983230-cbd13700-ca93-11e9-8f51-c3930a257702.png)

On Chrome, it returns it here:
![image](https://user-images.githubusercontent.com/11037431/63983273-f7542180-ca93-11e9-83dc-c38c6b133193.png)

The Chrome location is the "expected" location, which is why Firefox needs the workaround.

<br><br>

A similar thing is happening for the vertical text. On Firefox, the range's rect is being returned as follows:
![image](https://user-images.githubusercontent.com/11037431/63983315-28345680-ca94-11e9-9248-0cc8ce7375ce.png)

Whereas on Chrome, there are 0 rects. This is why the [```isPointInRange``` check](https://github.com/FooSoft/yomichan/blob/cd75f5b97dd47e252854d6381b49d2b7bc77c3ce/ext/fg/js/document.js#L174) returns false.

<br><br>

Some of these issues are likely coming from the fact that [```caretRangeFromPoint```](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint) is nonstandard,  and Firefox has to fallback to using [```caretPositionFromPoint```](https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/caretPositionFromPoint), which is also nonstandard. However, overall, it seems that both methods have some issues.
