### ISSUE TITLE
Just looking for some dictionary formatting advice

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#1910]
This dictionary I'm converting often has these big long lists of compound words at the end of entries. They aren't xrefs per se, just words that are grouped in the same physical location in the paper copy
![image](https://user-images.githubusercontent.com/35350819/130908884-3541a7b6-e367-46ec-8657-5dd2c568f2a3.png)
![image](https://user-images.githubusercontent.com/35350819/130908920-a8008f3c-761f-45c7-8de8-29b54cfc2005.png)

(btw, the dict uses this syntax for actual xrefs)
![image](https://user-images.githubusercontent.com/35350819/130909314-09666eeb-c1eb-45ba-894d-df80d0d31bfb.png)

I've tried to prevent it from taking up too much space by removing all the linebreaks and making the font smaller, but this is somewhat unsightly

A couple ideas I have are:
1. simply remove the section entirely
2. place the list in an svg, kinda like [this](https://github.com/FooSoft/yomichan/files/7051989/00046.zip). This would allow the list to be reduced to [Image], while keeping the text selectable
UPDATE: This probably isn't practical, as I would end up with over 90k SVG files....
3. use something like the [summary tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary). I assume this isn't possible without user CSS or structured content updates, though?

Anyone have any thoughts/suggestions? Thanks!

**Comment by toasted-nutbread** [comment]
I supposed it depends on how much value it adds. For the にほん example you pasted, that seems like extra noise that might not be all that helpful. SVG sounds like an idea with a lot of problems, like what you already mentioned, and it also comes with layout issues. The summary tag is an interesting idea, though it potentially poses some accessibility/workflow issues since it's not something that's done currently (e.g. it might not be easy to expand/collapse for keyboard-only users), and it could be difficult to add to Anki. It could potentially be set up similar to how the collapsible dictionaries functionality works, but that could also potentially be difficult, not sure how flexible that is off the top of my head.

Overall, I don't have a great suggestion other than information overload could potentially be negative with the Yomichan workflow; some people may not be interested in related/similar terms during regular use. I suppose you could create two variants of the dictionary also: one with, one without.

Related: #1165.

**Comment by Thermospore** [comment]
Hmmm thanks for the insight ✌️ 

Sometimes when the list is short I'll take a glance and find something interesting, but it generally doesn't serve much practical use

In reference to the example in the first post:
- for entries like 運動, the list is essentially the search results for `運動*`, which you could search yourself if you wanted
- for entries like 運動麻痺, the list simply links back to the root word 運動, which is already in your search results anyway

All things considered I think I'll just remove it
