### ISSUE TITLE
[Feature Request] Keep HTML format with {selection-text}

### ISSUE THREAD

**Issue by Skillesss** [FooSoft/yomichan#1929]
With the selection being turned to a string it makes it harder to visually identify separate definitions.

Example with JMdict English:
In Anki field and previewer: `but however still and regardless of whether (or not)`

In Anki html editor:
```
but
    however
    still
    and

    regardless of
    whether (or not)
```

Using `multiLine` or `formatGlossary` on `getMedia` doesn't really do it justice. They also makes it pretty hard to reformat with how `regexMatch` and `regexReplace` work right now. (#1928)

---
Yomichan 21.7.31.2

**Comment by toasted-nutbread** [comment]
What is your current use case for `{selection-text}`? Is it to only add certain definitions to the Anki card?

Exposing HTML-formatted selection text is a dangerous can of worms because it would require input sanitization to remove script tags and other undesirables. It would also be inconsistent with regards to what formatting is shown; e.g. `<span style="font-weight:bold">text</span>` would not be converted to `<b>text</b>` or `<strong>text</strong>`.

**Comment by Skillesss** [comment]
> What is your current use case for `{selection-text}`? Is it to only add certain definitions to the Anki card?

Yes. Mostly for when the lists are too long and becomes a wall of text when sent to Anki.
I have been using the snippet you've created here https://github.com/FooSoft/yomichan/issues/378#issuecomment-674539225 for a bit now. Though long lists become an issue as they become annoying to shorten in Anki overtime.

> It would also be inconsistent with regards to what formatting is shown; e.g. `<span style="font-weight:bold">text</span>` would not be converted to `<b>text</b>` or `<strong>text</strong>`.

Oh. I didn't think about that. I was thinking more along the lines of how manually copy and pasting the definitions work. The definitions still roughly keeps its list form while still keeping the bullet points in Anki. (I wonder if it's actually Anki setting the format and not Yomichan)

Copying from here:
![image](https://user-images.githubusercontent.com/30380089/132103367-5e25a6fd-3833-46db-8c93-22575e74bdd7.png)

Pasting into Anki:
![image](https://user-images.githubusercontent.com/30380089/132103439-176aabaa-7b9c-4a74-a0dc-cff0b3ada842.png)
html:
```html
<li><div><div><ul><li>cold (e.g. weather)</li></ul></div></div></li><li><div><div><div></div><ul><li>uninteresting (esp. joke)</li><li>lame</li><li>dull</li><li>weak</li><li>corny</li></ul></div></div></li>
```

**Comment by toasted-nutbread** [comment]
> Yes. Mostly for when the lists are too long and becomes a wall of text when sent to Anki.

In that case, this may be related to #1892, #1735, #1345. Yomichan probably needs a less hacky way of filtering what gets added to Anki cards.

> Oh. I didn't think about that. I was thinking more along the lines of how manually copy and pasting the definitions work.

Unfortunately this is something that cannot be done without forcing the browser to copy-paste the content, since this re-formatting is performed by the browser and the functionality is not directly exposed. I don't think this can be done arbitrarily, and even if it can, it's destructive to the prior contents of the clipboard, which is undesirable.

**Comment by Skillesss** [comment]
That is unfortunate 😢 
Thanks for the clarification.
