### ISSUE TITLE
[Feature Request] Add Chinese dictionary.

### ISSUE THREAD

**Issue by wildwestrom** [FooSoft/yomichan#2002]
I found this dictionary, [CC-EDICT](https://www.mdbg.net/chinese/dictionary?page=cedict), and I'd like to convert it to a format consumable by yomichan. 

Although I'm labeling this as a feature request, I'm really making this issue to ask for guidance on how to do this.

**Comment by Ceynou** [comment]
Must work with Yomichan Import
https://twitter.com/mattvsjapan/status/1323385773685526528

**Comment by wildwestrom** [comment]
Ok, I don't know golang unfortunately. I was hoping there was something like a json spec so I could convert it myself in a language I know.

**Comment by Ceynou** [comment]
You didn't have to know any language, just use the application Yomichan Import, but I tried and it's not supporting the format of your dictionary, however someone converted it and I'll assume I can post the link since they already shared their collection in Issue:
https://drive.google.com/drive/folders/1cQprswMScgMx7UDxfN-BsoTlPaDGheS6

**Comment by toasted-nutbread** [comment]
Here are some JSON schemas for how the dictionary format should look:
https://github.com/FooSoft/yomichan/tree/master/ext/data/schemas

The schema files have descriptions, and you can also unzip an existing Japanese dictionary (such as JMdict) to get a sense for how it looks internally. The files are all JSON.

**Comment by toasted-nutbread** [comment]
Related: #1911
