### ISSUE TITLE
Certain kotowaza not being picked up by parser

### ISSUE THREAD

**Issue by kelpso** [FooSoft/yomichan#2010]
**Description**
When using Yomichan on kotowaza which exists in the dictionaries, it is not recognised. The most recent example I have of this is when trying to parse ミイラ取りがミイラになる with the 大辞林 第三版 and 実用日本語表現辞典 dictionaries installed.  

In 大辞林 第三版, the phrase appears in `term_bank_27.json`, and the line has the contents:
`["ミイラ取りがミイラになる","","","",0,["ミイラ取りがミイラになる\n人を連れもどしに行った者が，逆に先方にとどまってしまう。また，説得におもむいた者が，かえって相手と同じ意見になってしまう。"],246875,""]`.

In 実用日本語表現辞典, the phrase appears twice in `term_bank_3.json`, and the lines have the contents:
`["ミイラとりがミイラになる", "ミイラとりがミイラになる", "", "", 0, ["ミイラ取りがミイラになる 読み方：ミイラとりがミイラになる\n人を探しに行った者が戻ってこない為に、逆に探される立場になること、あるいは、相手を説得しに行ったにもかかわらず、逆に説得されて相手と同意見になってしまうことを意味する諺。"], 22231, ""]`
`["ミイラ取りがミイラになる", "ミイラとりがミイラになる", "", "", 0, ["ミイラ取りがミイラになる 読み方：ミイラとりがミイラになる\n人を探しに行った者が戻ってこない為に、逆に探される立場になること、あるいは、相手を説得しに行ったにもかかわらず、逆に説得されて相手と同意見になってしまうことを意味する諺。"], 22232, ""]`

An example of this phrase from 実用日本語表現辞典 (the same dictionary as the second one above) can be found on Weblio at [this link](https://www.weblio.jp/content/%E3%83%9F%E3%82%A4%E3%83%A9%E5%8F%96%E3%82%8A%E3%81%8C%E3%83%9F%E3%82%A4%E3%83%A9%E3%81%AB%E3%81%AA%E3%82%8B). When attempting to use Yomichan on it, it only parses the ミイラ part in 大辞林 第三版 and ignores the rest. I have also attempted with a kana-only version of the string to no avail.

This happens with other phrases too, but I have nothing more that comes to mind at this point in time.

**Browser version**
Microsoft Edge 97.0.1069.0 

**Yomichan version**
21.9.30.2

**Exported settings file**
[yomichan-settings-2021-11-15-07-02-18.txt](https://github.com/FooSoft/yomichan/files/7536511/yomichan-settings-2021-11-15-07-02-18.txt)

**Comment by Thermospore** [comment]
I think you just need to bump up your `Text scan length` in the settings!

**Comment by kelpso** [comment]
You're right, thank you so much! Had no idea this was a setting.

**Comment by kuroahna** [comment]
Wow, thank you @Thermospore ! I didn't know this was a thing. Is there a reason why the default is set to `10`? Would it make sense to increase this to something like `25` or something larger as a "sensible" default for people who don't really know all the settings that Yomichan has to offer?

Also, I currently have it set to `100`. is there really any "downsides" to this? I assume it could potentially make Yomichan laggy since it could theoretically have to scan up to 100 characters when looking for terms.

**Comment by toasted-nutbread** [comment]
The default is 16 now, 10 was the default for older installations. Larger values will have a greater performance hit, as they scan for much longer text. The default is left relatively low since it's a decent tradeoff for most use cases. For users with many dictionaries installed, it could significantly bog down the system.
