### ISSUE TITLE
[Feature Request] Yomichan Search Page online

### ISSUE THREAD

**Issue by MarvNC** [FooSoft/yomichan#2048]
Would it be possible to have a version of the Yomichan search page on the web? The reason I ask is that I want to use [Google Input Tools](https://chrome.google.com/webstore/detail/google-input-tools/mclkkofklkfljcocdinagocijmpgbhab) with the Yomichan search page, and I believe extensions can't interact with other extensions' pages. Any other suggestion for using Google's handwriting recognition with Yomichan's search page would be appreciated as well.

**Comment by toasted-nutbread** [comment]
After a bit of experimentation, there doesn't seem to be a good way of doing this. Yomichan itself requires a bunch of special web extension APIs to function properly, so it can't run alone on something like a localhost server without losing a lot of its functionality. It's also not easily workable to get the extension to hijack an existing page (e.g. a blank page) to display its content, since a lot of the content it displays is dependent on it being part of an extension webpage.

**Comment by MarvNC** [comment]
Thanks for looking into it, that's unfortunate.
