### ISSUE TITLE
Does not work on a website with Chrome

### ISSUE THREAD

**Issue by arvin-z** [FooSoft/yomichan#2176]
**Description**
The popup does not show up when trying to scan words on this page: https://ieagent.jp/blog/eria/osusumeeki-11901
This issue only happens on Chrome. It works as expected on Firefox.

**Browser version**
Chrome 102.0.5005.115

**Yomichan version**
22.4.4.0

**Exported settings file**
[yomichan-settings-2022-06-18-06-02-22.txt](https://github.com/FooSoft/yomichan/files/8933030/yomichan-settings-2022-06-18-06-02-22.txt)

**Comment by toasted-nutbread** [comment]
This is apparently due to the website's use of the CSS `zoom: 1.13` property, which is nonstandard and highly discouraged from being used. It is only implemented on Chromium browsers, so that's why it works on Firefox, because it's not affecting the page.

I've set up a preliminary change to address this (#2178), but there are a lot of things that this can affect, so it's not complete.
