### ISSUE TITLE
Handling spaces

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan#23]
Hi, looking at this page for example,

https://www.jw.org/ja/%E5%87%BA%E7%89%88%E7%89%A9/%E6%9C%AC/%E8%81%96%E6%9B%B8-%E7%89%A9%E8%AA%9E/2/%E3%83%AD%E3%83%88-%E5%A6%BB/

The text seems to have hidden spaces that appear when copy and pasted, and Yomichan gets caught on them. Mainly it fails at deconjugating past and te-form verbs. I think it was working fine in 0.994 and broke in 0.995 (but maybe something changed on the website).

**Comment by FooSoft** [comment]
Yup, there are indeed to be hidden spaces (see those `nbsp` entities). This causes a problem because Yomichan thinks that these are breaks in words. I'll see about fixing this somehow.
![](http://i.imgur.com/GxmE2Ew.png)

**Comment by HelenFoster** [comment]
Something similar comes up on Satori Reader (separating things which could be looked up as one expression). They do have a built-in dictionary which recombines the fragments as appropriate, but still useful to use Yomichan sometimes. Not very important, but another example to consider if it's not too complicated.

https://www.satorireader.com/articles/news-neko-densha-edition-m

**Comment by FooSoft** [comment]
Fixed

**Comment by faneca** [comment]
Mmm, this is a double edged sword.

It works great on delvinlanguage.com when their automated segmentation tool gets things wrong (before, I couldn't extend the selection past a segment because of the furigana markup):

1.1.15
![multisegment-1 1 15-](https://cloud.githubusercontent.com/assets/1409227/26389421/2479403a-405a-11e7-8349-dc69db86e3d7.png)

1.1.17
![multisegment-1 1 17-](https://cloud.githubusercontent.com/assets/1409227/26389427/2ed76854-405a-11e7-83a7-c10df81a9ea4.png)

So this is much better now...

But, on the other hand, now I can't analyze a furigana section (for instance, to get alternative kanji spellings for a word -- the image below is not the best example for the use case, but shows the issue pretty well).

1.1.15
![furigana-1 1 15-](https://cloud.githubusercontent.com/assets/1409227/26389445/3eeb1588-405a-11e7-8cd5-4d6d6d367d83.png)

1.1.17
![furigana-1 1 17-](https://cloud.githubusercontent.com/assets/1409227/26389453/45a8e882-405a-11e7-830a-5f287a096de4.png)


If we need to choose between the two, I guess the new way is better... But I was wondering if it'd be possible to do something else without breaking current functionality. Like, for example, letting this wonderful extension analyze the furigana nonetheless *when the starting point* of the selection is already at it

**Comment by faneca** [comment]
For the sake of completeness, I forgot to mention this is in Firefox, and the relevant markup is this (indentation added):
```html
<div id="context-transcription" class="difficulty1" data-furigana="0" data-played="1">
    <span data-phonetic="さわぎ" data-ime="sawagi" class="region" data-clusters="12507">
        <ruby>騒ぎ<rp>(</rp><rt>さわぎ</rt><rp>)</rp></ruby>
    </span>
    <span data-phonetic="が" data-ime="ga" class="region" data-clusters="10120">
        が
    </span>
    <span data-phonetic="おさまっ" data-ime="osamaxtsu" class="region" data-clusters="12511">
        <ruby>収まっ<rp>(</rp><rt>おさまっ</rt><rp>)</rp></ruby>
    </span>
    <span data-phonetic="たら" data-ime="tara" class="region" data-clusters="10198">
        たら
    </span>、
    <span data-phonetic="うら" data-ime="ura" class="region" data-clusters="10785">
        <ruby>裏<rp>(</rp><rt>うら</rt><rp>)</rp></ruby>
    </span>
    <span data-phonetic="の" data-ime="no" class="region" data-clusters="10021">
        の
    </span>
    <span data-phonetic="くぐりど" data-ime="kugurido" class="region" data-clusters="12515">
        <span data-phonetic="くぐり" data-ime="kuguri" class="region" data-clusters="12513">
            くぐり
        </span>
        <span data-phonetic="ど" data-ime="do" class="region clozed" data-clusters="10012">
            <ruby>戸<rp>(</rp><rt>ど</rt><rp>)</rp></ruby>
        </span>
    </span>
    <span data-phonetic="から" data-ime="kara" class="region" data-clusters="10234">
        から
    </span>
    <span data-phonetic="で" data-ime="de" class="region" data-clusters="11028">
        <ruby>出<rp>(</rp><rt>で</rt><rp>)</rp></ruby>
    </span>
    <span data-phonetic="られる" data-ime="rareru" class="region" data-clusters="10352">
        られる
    </span>。
</div>
```

**Comment by faneca** [comment]
And, as a final note, I've now seen this is more related to issues #30 and #50 than to this one. As I jumped directly from 1.1.15 to 1.1.17, I got a little confused. Sorry, feel free to move my description to where you consider it more appropriate.

**Comment by FooSoft** [comment]
As you mentioned, the change in behavior does intentionally prevent users from scanning `rt` tags. There is simply no way to make text with furigana interlaced in the content work without disabling them. I can see that it may be inconvenient if you were relying on the old behavior, but you also have to realize that your usage case would actually only be valid for a subset of all cases. For example, in your case the furigana for 騒ぎ is written as <ruby>騒ぎ<rt>さわぎ</rt></ruby>. On other sites, it may be written as <ruby>騒<rt>さわ</rt>ぎ</ruby> (which would actually make more sense), so what you are trying to do wouldn't work anyway (since you would search for さわ and not さわぎ). There are even more complications for longer words where there are multiple Kanji included and the `rt` tags are interlaced with the characters.

**Comment by faneca** [comment]
Ok, fair enough. As I said, if we can't have both, it makes a lot more sense to let it be as it is now.

Another alternative that comes to mind (please, bear with me ^_^;) is to have a switch (a keyboard modifier, a "toolbar widget" toggle, an extension option, etc.) to alternate between ignoring the rt part of every ruby (its current behavior) and exactly the opposite: ignoring every non-rt part of them (e.g. by using shift+ctrl or shift+alt while scanning).

In any case, I admit this is for a narrow use case which could possibly covered by other means.

**Comment by FooSoft** [comment]
I think this might be a situation where we should think about what you are trying to accomplish instead of how you want to accomplish it. What if  the furigana string in the definition window were clickable (kind of like the Kanji are), and upon clicking it, Yomichan would redo the search using the hiragana?

**Comment by faneca** [comment]
Yep, that would definitely do. I'll open a proper, separate issue for it. Thanks! (here: #53)
