### ISSUE TITLE
Custom CSS user instructions

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#242]
A while ago, I noticed that you can add custom CSS to Yomichan, but I still can't manage to get it working. I think a little section in the options page that dictates its usage would be insightful enough for anyone trying to add a little flare to their own Yomichan.

With this new feature, I've been wondering if it's possible to achieve an inversion of colors to simulate a dark mode. Please let me know if this possible and how it would be done.

**Comment by toasted-nutbread** [comment]
This is a feature I added to provide a quick and dirty way to make some tweaks to the internals of the popup. Technically you should be able to adjust any of the visual styles, but it doesn't have the best workflow for doing so. I may need to add some sort of live view of a popup to show what the results look like, because currently it requires a full page refresh of any webpage using yomichan before the differences will be shown.

Adding a dark mode using the current settings is entirely possible assuming you are familiar with CSS rules and the underlying HTML structure, it just isn't a great workflow currently. The only things you won't be able to change are styles which are outside of the popup, for example the drop shadow is currently not able to be adjusted. I've been considering experimenting with [shadow DOMs](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) to potentially provide more options here, but I can't say for sure how well that would work.

**Comment by oudajosefu** [comment]
Figured it out. This is a nice solution to having a dark mode:
```
body {
    color: #fff;
    background: #000;
}
.expression .kanji-link {
    color: rgb(191, 191, 191);
}
.glossary-item {
    color: #fff;
}
```

**Comment by oudajosefu** [comment]
I'm actually gonna try implementing this as a toggle on the options page, so I will keep this open for now until I do so. Or maybe I should open another issue for that?
