### ISSUE TITLE
Code style for private variables/functions

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#258]
Open questions about code style regarding the intended scope of use for variables and functions. I don't want to make significant stylistic changes unless others collaborators think there is merit to them.

1. One thing I've noticed while implementing some new features is that it's not immediately apparent whether class functions and variables are intended to be private/internal, or if they are also designed to be used externally. Same can apply to variables/functions defined on the global object: is the function intended to be publicly used or is it a local helper function. This can make it take longer to make changes, since you not only have to check references within the same file, but other files as well.

   A common convention is to prefix internals with a ```_``` as a hint that this is a private member. Does anyone else feel that this would be a beneficial change? Or any other motivations for or against?

2. There is a similar namespacing issue with functions being declared on the global object, which seems to be why some functions have prefixes like ```api*``` or ```audio*```. Would it make sense to create classes which encapsulate some of these functionalities?

   For example, in the case of the ```api*``` functions, would it make sense to do something like create a ```FrontendAPI``` and ```BackendAPI``` class? The public functions would be the same, but putting it into a class might make the encapsulation more clear. The end result might be something like:
   ```js
   const api = new FrontendAPI(); // or new BackendAPI();
   // ...
   await api.optionsGet(); // instead of old apiOptionsGet();
   ```
   This is somewhat similar to how the ```AnkiConnect/AnkiNull``` and ```Popup/PopupProxy``` pairs of classes work.

**Comment by siikamiika** [comment]
I think many of the namespacing issues come from the nature of JavaScript in web browsers that is adding scripts into HTML in some order and hoping that other code running on the page doesn't have any name conflicts with it and that your own code doesn't immediately run something that depends on stuff that's in a script tag below.

JavaScript has been improving steadily on this and the most promising feature IMO that doesn't require a transpiler is [ES6 modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). I tried to use them for a feature in the past, but had to [revert](https://github.com/FooSoft/yomichan/pull/172/commits/0ee6d05cb15a8bc94f120c2896e7537fd969aaed) because content scripts don't support modules yet. So we're either stuck with the traditional way of using JavaScript or have to use a transpiler that turns everything into a single script file. Modules would allow the following:

```javascript
import * as name from "module-name";
```

1. You've contributed a lot to the codebase lately, and as the project size grows, I agree that it would help to have some way of indicating the that an attribute/method is private. Maybe even some additional refactoring for the components, such as creating subdirectories, could be beneficial. You already did the same for the settings menu (as it's displayed to the user).

    I come from a Python background where it's also common to prefix private attributes and methods with a `_`, but I saw an [ES proposal](https://github.com/tc39/proposal-private-methods) where a `#` is used instead. That's not going to work in all browsers for quite a while if ever so until then `_` works fine in my opinion.

2. This comes back to what I mentioned earlier about modules, but classes can be used for this when lacking a better tool. I think that in programming languages like C where creating namespaces is more awkward it makes sense to use the prefix style instead. In my opinion it doesn't matter much which style you use if you stick to it and use it consistently across the codebase, but with a class it's easier to enforce that every related function goes into the same name or "prefix" space.

**Comment by FooSoft** [comment]
1. Regarding the distinction about public and private data in scripting languages like JavaScirpt (as opposed to more strictly typed languages like C# and C++ which have features to enforce this difference), my approach has just been to attempt to write code in a way that assumes that anything that any data that can be messed with, will probably be messed with. That means that any method on a class should be reasonably callable, and will not modify the object in an unexpected way. This can be accomplished by keeping the mutable state of any given object to a minimum. This might mean that you have to pass more arguments around, but it protect you from situations in which methods must be called in a very particular order, or everything goes to hell. Regarding getters and setters, I generally do not think they are necessary, unless they are performing actual work (or might have to in the future). So basically my personal guidelines are:
* Write the least amount of code possible to keep things simple; don't try to make things more robust then they have to be (we as developers are often bad at predicting which areas will need flexibility).
* Keep the amount of mutable state in an object to the minimum, and name methods in such a way so that it is very clear as to how they are mutating the state.
Regarding having some sort of a convention about hinting to other developers about what a "private" field is, I think that is fine to use a prefix. Something like `_` would probably be best, as it is common in languages outside of JavaScript as well.
2. I don't particularly like the idea of using classes as namespaces for grouping related functions together. The problem with it is that people will inevitably end up passing them around, and it gets to be a headache when you realize you need to access additional APIs (so you need to plumb through more stuff), or you have classes that alias APIs to different names (in your example, you do `const api = new FrontendAPI();`); now imagine lots of other code doing the same thing for other APIs as well... This makes it much harder to search the codebase for where particular functions are being used.

**Comment by toasted-nutbread** [comment]
Thanks for the feedback, it's helpful to know what the general thoughts are topics like this are so I don't do anything that drastically strays from expectations.

To provide some further background on why I bring up #&#8203;1, consider a few of the following examples:
* **Internal variables**
    [```Popup.visible```](https://github.com/FooSoft/yomichan/blob/03c72e94290fdb1e77f1ca247efb526a0dc9f44e/ext/fg/js/popup.js#L38) variable vs [```Popup.isVisible()```](https://github.com/FooSoft/yomichan/blob/03c72e94290fdb1e77f1ca247efb526a0dc9f44e/ext/fg/js/popup.js#L246-L248) and [```Popup.setVisible()```](https://github.com/FooSoft/yomichan/blob/03c72e94290fdb1e77f1ca247efb526a0dc9f44e/ext/fg/js/popup.js#L250-L253).
   The member variable is used to store the current internal state, but only ```isVisible()``` and ```setVisible()``` are intended to be used externally. There is nothing that indicates that ```.visible``` shouldn't be used from other sources.

* **Class helper functions** (both static and non-static)
   [```TextSourceRange.seekForwardHelper()```](https://github.com/FooSoft/yomichan/blob/721248c8210c2fb386b765eb518580765091fa67/ext/fg/js/source.js#L121-L151), used internally by [```TextSourceRange.seekForward()```](https://github.com/FooSoft/yomichan/blob/721248c8210c2fb386b765eb518580765091fa67/ext/fg/js/source.js#L104-L119).
   ```seekForward``` is the only function that is used externally, and while it would certainly be possible to use ```seekForwardHelper``` externally, ```seekForward``` is the intended public API. ```seekForwardHelper``` could be considered an implementation detail of ```seekForward```.

   This code has since been replaced, but I'm referencing it as an example of something that I didn't write.

* **Global helper functions**
   [```fg/apiGetEnvironmentInfo```](https://github.com/FooSoft/yomichan/blob/03c72e94290fdb1e77f1ca247efb526a0dc9f44e/ext/fg/js/api.js#L72), [```bg/apiGetEnvironmentInfo```](https://github.com/FooSoft/yomichan/blob/03c72e94290fdb1e77f1ca247efb526a0dc9f44e/ext/bg/js/api.js#L274), and [```bg/apiGetBrowser```](https://github.com/FooSoft/yomichan/blob/03c72e94290fdb1e77f1ca247efb526a0dc9f44e/ext/bg/js/api.js#L285).
   As mentioned before, it seems that the background API is intended to have parity with the foreground API. However, in this example, the ```bg/api.js``` has a function ```apiGetBrowser``` which is not present in the foreground version. This is because ```apiGetBrowser``` is intended to be a helper function for ```apiGetEnvironmentInfo```, but there is no indication that this is intended to be the case. So someone might mistakenly use ```apiGetBrowser```, and it would work on the background but not the foreground.

IMO, in all 3 examples, prefixing with an underscore would clarify the intent, both in the declaration and the usage.

> That means that any method on a class should be reasonably callable, and will not modify the object in an unexpected way.

I fully agree with this in the context of variables/functions which are intended to be public. Just wondering if this practice extends to things which could be considered internals of the implementation.


With regards to #&#8203;2, I see your concern and appreciate the explanation. I will refrain from doing anything unwarranted.

**Comment by FooSoft** [comment]
Yeah, I generally agree with that reasoning. Using a `_` prefix for "private" members and methods seems reasonable to me. If anything, it is a common convention that will help new contributors understand what things they generally should or should not mess with on objects.

That being said, I think the best approach may be to make "helper" features be completely unusable outside their intended context by reducing the scope in which they are visible/accessible. From your example, for instance, `apiGetBrowser` can just be an arrow function inside of `apiGetEnvironmentInfo`; this would allow you to continue thinking of it as being a separate unit of work, while avoiding expanding the API in general.

**Comment by toasted-nutbread** [comment]
Thanks for the feedback; my questions are answered.
