### ISSUE TITLE
Make search page open up on search bar every time

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#263]
When the search page is opened, the search bar immediately allows you to start typing without clicking on it. I'd like this feature to always remain active. The time that it doesn't stay active is when you hover over the results to display popups. It resultantly loses its focus on the search bar and makes it so that the next time you want to open that search page, you have to re-click the search bar.

I looked through the commits in #261, but I didn't really understand it enough to add this ability, and I definitely would have added it if I had the proper expertise.

**Comment by siikamiika** [comment]
I'm not sure if it would make sense to make the input box focused at all times when on the search page, because you can also use keyboard shortcuts there. Right now none of the shortcuts seem to collide with normal typing, but in the future some could.

Is your primary problem that the focus is lost after scanning, or do you think it would help if the search page hotkey also focused the input box?

**Comment by oudajosefu** [comment]
@siikamiika I think it would help if the search page hotkey focused the input box every time even when the search page already exists and you just want to refocus on that tab like mentioned in #260. The primary problem is that because the focus is lost after scanning, refocusing on an already existing search page tab doesn't open with focus on the input box.

**Comment by siikamiika** [comment]
@oudajosefu The fix now makes Yomichan actually focus the query element on every key press (not only the search page hotkey) that isn't used by Yomichan for anything, and it also skips some other keys that are used for normal interaction with text like copy/paste. I have tested it on Linux, but let me know if there are problems on Mac.
