### ISSUE TITLE
Dictionary pops up when highlighting text in "Mobile/Responsive design mode" (Chrome)

### ISSUE THREAD

**Issue by shanrauf** [FooSoft/yomichan#271]
In the Chrome Developer Tools (F12) when selecting the Device/Mobile mode button at the top left (used frequently for responsive web development), clicking text on the webpage causes a Yomichan popup to open (attached GIF below), interefering with any interaction with the site. Additionally, holding down the lookup hotkey to highlight text and see the word's definition does not work in this mode.

This does not appear to happen when I try replicating the issue on Firefox.

![JQYxUlhkQW](https://user-images.githubusercontent.com/40217167/67820105-23305b00-fa75-11e9-8f7f-123aefa4cba0.gif)

![ju6IX8KpQo](https://user-images.githubusercontent.com/40217167/67820417-54f5f180-fa76-11e9-93fd-27cf3389be34.gif)

**Comment by toasted-nutbread** [comment]
This is the expected functionality. When you enter the responsive design mode, Chrome simulates touch events rather than using the mouse cursor. For mobile device support, scanning requires the text to be touched, which is what is simulated when you are clicking with the mouse. The scanning hotkey doesn't work since there is no mouse cursor simulated in this mode. I don't know if Chrome has a way to change this behaviour, since I've never looked into it, but maybe there's a way.

Firefox treats its responsive design mode a bit differently, in that enabling touch input is a separate option.

If it's helpful, it is possible to disable touch event handling by disabling the "Touch input enabled" option under the "Scanning Options" heading on the settings page.

**Comment by shanrauf** [comment]
@toasted-nutbread Didn't know that setting existed, thanks!
