### ISSUE TITLE
[Bug Report] Pulling wrong word on netflix

### ISSUE THREAD

**Issue by edoreld** [FooSoft/yomichan#276]
I'm using the subadub extension to make Netflix subtitles highlightable. 

When I then use yomichan's "Add to Anki" functionality (the big green + button) on Netflix, the card is added to Anki but for some reason the last word of the current episode's title is added to the beginning of yomichan's {sentence} field.

How to reproduce:
1. Install SubaDub, Yomichan, Anki, AnkiConnect
2. Set up Yomichan integration with Anki
3. Open episode in Netflix ([ex](https://www.netflix.com/watch/80240866?trackId=13752289&tctx=0%2C1%2Cbd44b0bb3be55a2f2421a5c980f7d469d8fe5ca5%3Ac2f366debda0a1b6b78ca6bd2436659dc90a1cf5%2C%2C))
4. Highlight word with Yomichan
5. Click on big, green + button.

When word is added to Anki, the episode's last word will be added to the beginning of the expression field. 

Related issue on subadub's repo: https://github.com/rsimmons/subadub/issues/9

**Comment by toasted-nutbread** [comment]
The issue is likely on Yomichan's side. The issue stems from the difficulties in determine what the sentence bounds are of the scanned word. The current method heavily relies on the assumption that there will be some sort of delimiting characters around the sentence, which is not always the case. Therefore, the [docSentenceExtract](https://github.com/FooSoft/yomichan/blob/b05960967098262c619e28be5238539c26b7b697/ext/fg/js/document.js#L142) function would likely need some tweaking. It's difficult to have it capture every use case due to the complexities of HTML and CSS, but I definitely think there are some improvements which are possible.

Related: #273, #221

**Comment by oudajosefu** [comment]
As a temporary fix, I suggest adding a regex formatting tool as mentioned in #273. This will allow @edoreld to delete parts of the {sentence} that shouldn't be there, given it's something matchable by regex.

**Comment by FooSoft** [comment]
It might be worthwhile to have different profiles for "sentence" extraction, as it may simply not be possible to come up with a solution that everyone is happy with. We've already seen requests from other users who want to save out "sentences" which are not really sentences at all.

**Comment by edoreld** [comment]
Thanks, I haven't tried it the regex replace thing yet, but if it works as advertised, it looks to be a possible solution.

**Comment by toasted-nutbread** [comment]
FYI: You are now able to test templates on the settings page. Syntax errors will also show exception information that handlebars returns. Unfortunately, the sentence context is empty, so you can't directly test that value, but other placeholders can be used.

184cc4cf28594f3bef9e141a8cbf9d7eb7a39e88

---

![image](https://user-images.githubusercontent.com/11037431/68535352-2813cb00-030f-11ea-9942-8920dda86fb4.png)
