### ISSUE TITLE
furigana bug

### ISSUE THREAD

**Issue by Geniusssmit** [FooSoft/yomichan#281]
just seen that word
![image](https://user-images.githubusercontent.com/24941285/68890928-f6e13380-0730-11ea-8a45-b7b3e5216876.png)

**Comment by siikamiika** [comment]
Duplicate of #94.

In short, it's not possible to get the furigana right without some level of guessing using shorter words in the dictionary (not perfect, see https://github.com/FooSoft/yomichan/issues/264#issuecomment-545143944), which would add a performance penalty that goes against the goal of making Yomichan faster.

It would be quite easy to check if there are many possible ways to distribute furigana for a word and fall back to showing the whole reading including kana already in the word, so that's something I might look into in the near future.
