### ISSUE TITLE
What are the "open book with arrow" icons in the popup? Also, sticky headers for results

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#301]
What do these do, because clicking them seems to do nothing. The tooltips say that the right pointing one is supposed to go the next term but does that mean the next term in the original sentence because that doesn't work? Also, the positioning of these icons is very unsatisfying and overall out of place.

**Comment by oudajosefu** [comment]
Actually, testing them a bit further has led me to believe that they literally don't do anything at all.

**Comment by siikamiika** [comment]
> What do these do, because clicking them seems to do nothing.

Before the change, only the left arrow existed on the top right side of each term. It was used to go to the previous, or "source" term after viewing a kanji or clicking a term. Now, it's moved to the top and it's always visible, even when you have scrolled the top right corner of a term out of view. There is also a second button that is used to go forward in history so that you can go back to a term or kanji without clicking it again. In addition to clicking the buttons and using the hotkeys in the tooltips, you can use the mouse wheel, either with shift anywhere or without a modifier mouse cursor on top of the buttons to navigate the history.

> Also, the positioning of these icons is very unsatisfying and overall out of place.

After seeing how they work and re-evaluating their function, I'd like to hear your opinion on these questions:

- Should they be hidden when no history is available, instead of using opacity? I agree that they add noise to a place where you usually look first when scanning a word.
- Would it be better if they were positioned in top middle or top right corner instead? I had them in the middle at some point while testing, but never pushed that to master.

**Comment by oudajosefu** [comment]
@siikamiika Ahh, I understand now, thanks for the clarification.

> Should they be hidden when no history is available, instead of using opacity? I agree that they add noise to a place where you usually look first when scanning a word.

I think that is a great idea. That would annoy people less if they turn the "Enable search when clicking glossary entries" option off and so never really have a _history_.

> Would it be better if they were positioned in top middle or top right corner instead? I had them in the middle at some point while testing, but never pushed that to master.

The top right corner would be best in my opinion. However, checking the design out again gave me an even better idea. It's a little hard to explain but bear with me. The top most word with the furigana should always stay at the top of the popup despite scrolling down the definition if it is a particularly lengthy one. When you scroll down far enough to reach the next term adn the last is completely out of view, that current term should take over and again stay at the top despite scrolling. If you implement this design, then maybe the left and right arrow icons can go in between the yellow asterisk icon and the sound icon.

**Comment by siikamiika** [comment]
@oudajosefu I've pushed a change that moves the buttons to top right, but I don't have access to a build environment for the templates to make them hidden yet. I'll see about the other suggestions later

**Comment by toasted-nutbread** [comment]
Your idea for using sticky elements is something I've thought of a few times. At a minimum, it would be a good idea to update the HTML to be able to support the sticky style, even if it's not used yet. People may or may not like that type of change, but it would at least allow it to be customized using custom CSS.

The button layout needs some thought in general. The difficulty is that it's a balancing act of several things:
* Making the info not look too busy.
* Making the actions clear.
* Working with limited space (default popup size is 400x250).
* Supporting multiple methods of presenting the info ("Result grouping" option).
* Making changes in ways that the users won't be confused by.

#292

**Comment by siikamiika** [comment]
I personally don't like sticky headers in general, but that could be because they're abused so much on sites that don't really need it, or they're made absurdly tall. There could be some business reasons behind those decisions such as brand promotion.

In this case it could be really useful because you don't always remember which term you're viewing after scrolling down a bit. Scrolling back up will interrupt the flow. If height usage is a problem, the sticky header could be togglable or activated with mouseover.

**Comment by siikamiika** [comment]
@oudajosefu 
https://github.com/FooSoft/yomichan/commit/3c749f87053fea88221453f4a6fe4f194726bb6e

**Comment by toasted-nutbread** [comment]
Resolving for now since the original question was answered, and implementing sticky headers for terms is likely not going to be done by default for the application, but may be accomplished via custom CSS rules.
