### ISSUE TITLE
Popup preview slow to appear

### ISSUE THREAD

**Issue by oudajosefu** [FooSoft/yomichan#302]
Seems like a recent pull broke the popup preview because it's not showing me anything. Let me know if you'd like my current settings to reproduce if it's working for you.

**Comment by oudajosefu** [comment]
Now it takes too long to appear. Possibly because you make it asynchronous?

**Comment by toasted-nutbread** [comment]
What browser? Can you test opening the page `chrome-extension://.../bg/settings-popup-preview.html` and see if it has similar lag?

On Chrome, I am seeing a ~1 second delay on the settings page, but marginal delay using the embedded page directly. Firefox I see marginal delay in both places.

**Comment by oudajosefu** [comment]
This is on Chrome. That page works fine and quickly, however the settings page does not. When I refresh the settings page, [this](https://streamable.com/1uq3a) is what happens.

**Comment by siikamiika** [comment]
@oudajosefu There were some additional changes to the popup preview, can you check if it's still slow to appear? For me Chrome and Firefox open quickly.

**Comment by oudajosefu** [comment]
Yes it is still occurring. I have six dictionaries installed if that helps.

**Comment by toasted-nutbread** [comment]
So doing some timing, I'm seeing about a 2-3 second delay when the popup preview is opening. The issue seems to be coming from the calls of [`getAllFast`](https://github.com/FooSoft/yomichan/blob/2a19d8c59f31e47f28e8b32b5fcd7edb1621c759/ext/bg/js/database.js#L649-L660) from [`findTermsBulk`](https://github.com/FooSoft/yomichan/blob/2a19d8c59f31e47f28e8b32b5fcd7edb1621c759/ext/bg/js/database.js#L142-L175). Doing a simple timing using [`performance.now()`](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now).

```js
static getAllFast(dbIndex, query, context, processRow) {
    return new Promise((resolve, reject) => {
        const t1 = performance.now();
        const request = dbIndex.getAll(query);
        request.onerror = (e) => reject(e);
        request.onsuccess = (e) => {
            const t2 = performance.now();
            for (const row of e.target.result) {
                processRow(row, context);
            }
            console.log('getAllFast', context, t2 - t1);
            resolve();
        };
    });
}
```

Example results:
```
getAllFast 0 2705.6499999998778
getAllFast 0 2706.145000000106
getAllFast 1 2706.3650000000052
getAllFast 1 2706.470000000081
getAllFast 2 2706.474999999955
getAllFast 2 2706.5599999996266
getAllFast 3 2706.640000000334
getAllFast 3 2706.699999999728
getAllFast 4 2706.7449999995006
getAllFast 4 2706.810000000587
getAllFast 5 2706.8550000003597
getAllFast 5 2706.919999999627
getAllFast 6 2707.0050000002084
getAllFast 6 2707.08999999988
getAllFast 7 2707.1549999991475
getAllFast 7 2707.2900000002846
getAllFast 8 2707.405000000108
getAllFast 8 2707.474999999249
getAllFast 9 2707.530000000588
getAllFast 9 2707.7149999995527
getAllFast 10 2707.7699999999822
getAllFast 10 2707.825000000412
getAllFast 11 2707.8700000001845
getAllFast 11 2707.934999999452
```

So in this case, the issue is coming from [`IDBIndex.getAll`](https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/getAll) taking 2.7 seconds. I don't know if there is anything that can be done to fix this.

Aside @ other devs: I have added the `Timer` class I use for debugging to the project so I don't lose it on an archaic branch: 47feb95842eac8e2fb4571a5ec493454cc0c422e. Can be used as such:
```js
async function something() {
    const t = new Timer('name');
    doWork();
    t.sample('doMoreWork');
    await doMoreWork();
    t.complete(); // will log a console message
}
```

**Comment by toasted-nutbread** [comment]
For additional reference, I am also seeing the issue in a24146538c94f0871c7ae91d4ebb9f663c22acf8. So if this is a recent issue, it wasn't caused by anything in the range a24146538c94f0871c7ae91d4ebb9f663c22acf8...47feb95842eac8e2fb4571a5ec493454cc0c422e. Same going as far back as 7d9d45ae10302582ce7431bd72ec4f8604dc5e65...47feb95842eac8e2fb4571a5ec493454cc0c422e.

Also tested in Google Chrome 78.0.3904.108 (Official Build) (64-bit), same results.

**Comment by siikamiika** [comment]
For me this only seems to be a problem on Chrome 78/Linux if I try to open the popup right after reloading the page. There's always one query that takes about 2.6 seconds and blocks the subsequent queries until it's finished. I'm not seeing everything take so long. I wonder if it's related to caching the index or something, I have quite a lot of memory.

```
// reload settings page
database.js:659 getAllFast 0 12.684999965131283 []
database.js:659 getAllFast 0 13.414999935775995 []
database.js:659 getAllFast 1 13.550000032410026 (4) [{…}, {…}, {…}, {…}]
database.js:659 getAllFast 1 13.860000064596534 []
database.js:659 getAllFast 2 13.970000203698874 []
database.js:659 getAllFast 2 14.084999915212393 []
database.js:659 getAllFast 3 14.190000016242266 [{…}]
database.js:659 getAllFast 3 14.315000036731362 []
database.js:659 getAllFast null 14.574999921023846 (3) [{…}, {…}, {…}]
database.js:659 getAllFast 0 6.61499984562397 (3) [{…}, {…}, {…}]
database.js:659 getAllFast 0 2545.399999944493 (4) [{…}, {…}, {…}, {…}]0: {expression: "読む", reading: "よむ", definitionTags: "v5m vt", rules: "v5", score: 703, …}1: {expression: "読む", reading: "よむ", definitionTags: "v5m vt", rules: "v5", score: 702, …}2: {expression: "読む", reading: "よむ", definitionTags: "v5m vt", rules: "v5", score: 701, …}3: {expression: "読む", reading: "よむ", definitionTags: "", rules: "vt v5", score: 0, …}length: 4__proto__: Array(0)
database.js:659 getAllFast 0 0.4350000526756048 []
database.js:659 getAllFast 1 0.5699999164789915 []
// open popup preview
database.js:659 getAllFast 0 1.4299999456852674 []
database.js:659 getAllFast 0 1.6899998299777508 []
database.js:659 getAllFast 1 1.8050000071525574 []
database.js:659 getAllFast 1 1.9050000701099634 []
database.js:659 getAllFast 2 2.0099999383091927 []
database.js:659 getAllFast 2 2.1100000012665987 []
database.js:659 getAllFast 3 2.2100000642240047 []
database.js:659 getAllFast 3 2.3200002033263445 []
database.js:659 getAllFast 4 2.409999957308173 []
database.js:659 getAllFast 4 2.4999999441206455 []
database.js:659 getAllFast 5 2.6149998884648085 []
database.js:659 getAllFast 5 2.7149999514222145 []
database.js:659 getAllFast 6 2.814999781548977 []
database.js:659 getAllFast 6 2.9100000392645597 []
database.js:659 getAllFast 7 3.005000064149499 []
database.js:659 getAllFast 7 3.109999932348728 []
database.js:659 getAllFast 8 3.2049999572336674 []
database.js:659 getAllFast 8 3.2999999821186066 []
database.js:659 getAllFast 9 3.4100001212209463 (4) [{…}, {…}, {…}, {…}]
database.js:659 getAllFast 9 3.5749999806284904 []
database.js:659 getAllFast 10 3.6800000816583633 []
database.js:659 getAllFast 10 3.7799999117851257 []
database.js:659 getAllFast 11 3.8850000128149986 [{…}]
database.js:659 getAllFast 11 4.010000033304095 []
database.js:659 getAllFast 0 0.25500007905066013 (3) [{…}, {…}, {…}]
database.js:659 getAllFast 0 0.23499992676079273 (4) [{…}, {…}, {…}, {…}]
database.js:659 getAllFast 0 0.17499993555247784 []
database.js:659 getAllFast 1 0.30000018887221813 []
```

**Comment by siikamiika** [comment]
Or maybe we should contact this guy https://randomascii.wordpress.com/ :smile:

**Comment by siikamiika** [comment]
Correction to the previous: I'm also seeing the consecutive slow performance timer results on Chrome if I try to open the popup preview before the slow query has finished. This seems to indicate that the timers are started but the query is blocked.

**Comment by toasted-nutbread** [comment]
So I forgot that this was even an issue, but the cause is due to Chrome's incredibly slow speeds at counting database entries ([`IDBIndex.count()`](https://developer.mozilla.org/en-US/docs/Web/API/IDBIndex/count)).

The reason why these counting operations are performed is to do database validation, making sure entries haven't been deleted and that there isn't data that doesn't belong to any installed dictionary (can happen if import fails).

This also illustrates that apparently Chrome's IndexedDB calls aren't run in parallel, since this count operation is blocking other operations.

https://github.com/FooSoft/yomichan/blob/47feb95842eac8e2fb4571a5ec493454cc0c422e/ext/bg/js/database.js#L293-L333

**Comment by toasted-nutbread** [comment]
This also raises the question of how to address #270's _Detect when databases have been automatically purged by the browser._ This would need to do something very similar to what's being done every time the settings page is opened, but instead only run on startup. So this operation could be implemented such that it runs ones and the results are stored (until the database is updated again), and that would fix the issue on the settings page.

However, it would mean that there would be that 2-6+ second startup delay before scanning would work on any webpage. That may be an acceptable delay, but I'm not sure what if that value can ever be extreme, e.g. something like a minute of wait time.

**Comment by oudajosefu** [comment]
> However, it would mean that there would be that 2-6+ second startup delay before scanning would work on any webpage. That may be an acceptable delay, but I'm not sure what if that value can ever be extreme, e.g. something like a minute of wait time.

That honestly sounds awful... on second thought, I can live with the settings page preview delay.
