### ISSUE TITLE
[Firefox] Feature request and bugs: RikaiCake, search form scan, on/off button, audio...

### ISSUE THREAD

**Issue by erasedff** [FooSoft/yomichan#31]
First of all, thank you for porting this extension for Firefox. Overall it works fine but there are some bugs and room for improvement.
1. I use Yomichan for Chrome and you could toggle the extension on/off by clicking the extension icon but Firefox doesn't have this functionality. This feature also disappeared from the Chrome version of Yomichan, I believe it was available pre-x.x.16?
2. Search form scan works really wonky in Firefox, same as in Chrome. Looks like another string of text is created on top of the text in the search form, here's how it looks like: http://i.imgur.com/oGXdKyt.png
Selecting text becomes a nuisance with strings overlapping each other. Rikaichan doesn't have this issue.
3. If the audio for a word is missing, you get a long long speech "this audio is unavailable, it will be added shortly blah-blah". It should probably be changed to the Chrome's short sound cue.
4. Would it be possible to ship Firefox extension with RikaiCake dictionary? Link to dict: https://addons.mozilla.org/en-US/firefox/addon/rikaicake-jp-en-dictionary/
5. If possible, some sort of built-in word search/lookup a-la Rikaichan would be nice to have.

**Comment by FooSoft** [comment]
Thanks for the comments!

1. Firefox does not appear to have an easy way to open extension options, and I would argue that having to right-click on the browser action button in Chrome is not that intuitive either. I want to make it dead simple for new users to be able to open the options page (they have to in order to install dictionaries for the extension to even function). You can still enable and disable the extension with one additional click (there is a checkbox in the options page now). 
2. I've noticed a couple of places where it misbehaves in Chrome but overall it seems to work okay... you are right about it looking kind of broken in Firefox. The problem is that we have to create a temporary overlay HTML element over the text field in order to get the word under the cursor (input forms do not support this behavior natively). Rikaichan avoids problems by immediately destroying this temporary HTML element, whereas I keep it around to show selection. If I can't find some sort of CSS fix I will probably have to switch Yomichan's behavior to do the same.
3. Known issue, I'm using the length of the audio clip to determine if the audio is placeholder or not. For whatever reason the length of the same mp3 file is returned as a different value in Firefox. Go figure. I just need to test for both values I guess.
4. I can add that dictionary to a list of built-in dictionaries that can be imported (like JMDICT or whatever) regardless of whether you are running on Firefox or Chrome. I will first have to see if there are any licensing issues with this though.
5. I agree, search would be awesome. I've been meaning to add it for some time but I haven't thought up of a good UI for it just yet. Suggestions are welcome.

**Comment by erasedff** [comment]
Thanks for the response.
1. Thought missing on/off switch was a bug, at least in Chrome anyway. Though having a quick turn on/off switch would be handy. Rikaichan works like that but I don't know how difficult it was to implement since I only know the basics of coding and know nothing about developing browser extensions.
2. Only tried google.com and jisho.org search forms so I don't know if it behaves differently on other websites. Assuming there's no cleaner workaround, maybe add a sub-option to turn off selection highlight within search forms? Would be pretty useful for jisho for example, since sometimes it doesn't break sentences correctly so I tend to use Rikaichan to search words directly in the search form and with Yomi it gets a bit messy and, at least in Firefox, you have to click a few times somewhere on the page in order for the overlay html to disappear, and if you don't and start typing more words then another overlay is created on top of the old one and it gets really clunky.
4. Yeah, I meant the built-in list. Don't know if there would be licensing issues but that dictionary is pretty neat when it comes to translating slang words and whatnot.
5. Personally I wouldn't even mind something similar to Rikaichan for starters. A simple toggle-able searchbar with hotkeys support. Maybe with some searchbar specific settings like independent pop-up size and number of words shown.

**Comment by FooSoft** [comment]
Everything except RikaiCake has been added. After having a brief glance through RikaiCake, I found that it doesn't really have enough material which is not already represented by EDICT to warrant writing a custom importer for it (not to mention RikaiCake is dead).
