### ISSUE TITLE
[Feature Request] Show readings for numerals written with Arabic numerals

### ISSUE THREAD

**Issue by pavlukivan** [FooSoft/yomichan#313]
Because these readings aren't quite intuitive, especially for exceptions like 1人 (Bad example because it's common, but you get the idea).

**Comment by siikamiika** [comment]
Do you mean that it's not possible to scan 1人 and 2人 etc because of the number?

In general, Yomichan should be able to do that when you enable "Search alphanumeric text" under Scanning Options, but JMdict seems to have those words with full-width digits (i.e. １人、２人), causing your example to not work.

Fixing this would require adding normalization such as [String.prototype.normalize](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) to all input and also to the installed dictionaries.

On the topic of normalization, maybe also UPPER/lowercase, ひらがな/カタカナ and even variant kanji should be normalized. Full/half-width normalization would be the only one that doesn't require a new schema, though.

**Comment by toasted-nutbread** [comment]
Resolved with #314's option **Convert numeric characters to full width**
