### ISSUE TITLE
Module-like design revisited

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#372]
One thing that became more apparent as I added the unit tests in #371 is that it can be difficult to set up all of the global dependencies.

https://github.com/FooSoft/yomichan/blob/1e573f36c416b3955b2e679c8f3ce7ffa91bf504/test/test-database.js#L13-L22

While it was fairly manageable for database.js, something like translator.js would be more difficult:

https://github.com/FooSoft/yomichan/blob/1e573f36c416b3955b2e679c8f3ce7ffa91bf504/ext/bg/js/translator.js#L19-L24

This could be simplified if add all of the `jp*`, `dict*`, etc. definitions were members of an object (e.g. `jp`) rather than globally defined. That way, only the `jp` or `dict` objects would have to be manually assigned to the global scope, which is much more manageable. If we were able to use `require` and modules, this is how it would have to be done anyways (`module.exports`).

This is something I previously brought up in #258, but it was decided to not do it, partially because there not being a strong reason to do so. I think unit tests may provide a stronger motivation for using this pattern. The alternative would seem to be transpiling, which is not really a desirable change.

**Comment by siikamiika** [comment]
I'm hopeful for getting module support to content scripts one day. Until then I think something like what's done with the `DOM` class could be an alternative: https://github.com/FooSoft/yomichan/blob/174d9e7429a0f7a45538e56a594ce627239d80c3/ext/mixed/js/dom.js#L20-L66
https://github.com/FooSoft/yomichan/blob/174d9e7429a0f7a45538e56a594ce627239d80c3/ext/mixed/js/text-scanner.js#L52

Every usage of `DOM.isMouseButtonDown` can be found from the codebase by name because the class isn't instantiated anywhere and only used statically.

This, provided that the functions are global in nature such the API functions, `jp*` functions or helpers like `isObject`. To me many of the `dict*` functions look like they could be a part of some class that deals with dictionary data such as `Translator` or another class that's used by it.

**Comment by toasted-nutbread** [comment]
> Every usage of `DOM.isMouseButtonDown` can be found from the codebase by name because the class isn't instantiated anywhere and only used statically.

Agreed, and it's also possible to do a singleton approach, like how the Yomichan class is designed.

https://github.com/FooSoft/yomichan/blob/0f46e3a093e7f0c07ad310d8c17e2582bdfd2741/ext/mixed/js/core.js#L267-L322

Which is how modules effectively work (`require` returns a shared object), and how browser libraries work (like `jQuery`, `$`, `wanakana`, etc. objects). There may be a small overhead of the additional property lookup, but that should be irrelevant.



> To me many of the `dict*` functions look like they could be a part of some class that deals with dictionary data such as `Translator` or another class that's used by it.

I agree on this as well; most of the functions seem like internal implementation details of `Translator`.

**Comment by toasted-nutbread** [comment]
For tracking, the changes made in #397, #399, #400, and #401 move in the direction of  what I was envisioning for this issue. State information is now tracked locally in a class instance rather than globally, and dependency injection is used to pass specialized implementation details to objects.

Closing this issue as further tasks related to this goal can be tracked separately and in https://github.com/FooSoft/yomichan/projects/5.
