### ISSUE TITLE
Audio doesn't get added to Anki for katakana words

### ISSUE THREAD

**Issue by Ooglogput** [FooSoft/yomichan#373]
When I import words to Anki, something like ライオン doesn't get audio added, but 来 or any other word with kanji works just fine. I didn't use to have this problem, but some combination of upgrading to Anki 2.1 or switching from Windows to Linux seemed to trigger this. Tried reinstalling with no luck.

**Comment by siikamiika** [comment]
I'm not sure if it has ever worked for katakana-only words when the audio source is jpod101, but it should be fixed in https://github.com/FooSoft/yomichan/commit/02e0e24153eb95b45057cfc92cadb6563b229cc1 which is unfortunately still in testing. You can install it here https://foosoft.net/projects/yomichan/index.html#installation

**Comment by Ooglogput** [comment]
I was confused for a moment since I was sure I was running testing already, but as it turns out I'm still on 1.8.8 and Firefox doesn't let me install from other sources without switching to another build. I'll hold out for a bit longer and try stable for now, but thanks for the heads up!
