### ISSUE TITLE
Stop making yomichan uglier with every update

### ISSUE THREAD

**Issue by Nekousagida** [FooSoft/yomichan#407]
First the unnecessary margins now this ugly as fuck font, what's your issue man

**Comment by siikamiika** [comment]
Could you elaborate? Yomichan is developed based on the needs of users and the developers themselves, but some users prefer more features and others want to keep everything the same. We are trying to address both, and there's a possibly relevant issue https://github.com/FooSoft/yomichan/issues/402 about improving the UX. I suggest giving your ideas there.

There's also an option to change the styles of Yomichan in the options if you know some CSS.

**Comment by toasted-nutbread** [comment]
> First the unnecessary margins

Has since been fixed; if this is still currently an issue, clarify.

> now this ugly as fuck font

The font has never changed; the CSS font definition has consistently been:

```css
"Helvetica Neue", Helvetica, Arial, sans-serif;
```

The most recent changes to CSS rules related to the font are f6621374817908ec5936caf635bae9bcd20b3ad1 and ceaeeb32dd23403c516f5aa5cb5527c40f2f21aa; [blame](https://github.com/FooSoft/yomichan/blame/master/ext/mixed/css/display.css#L38-L42).

Bootstrap v3.3.7 has the font as the same value for everything which predates those changes:
https://github.com/twbs/bootstrap/blob/v3.3.7/dist/css/bootstrap.css#L1085

Additionally, the display font is sometimes dependent on what fonts are installed on your operating system; this happened in #178.

**Comment by toasted-nutbread** [comment]
Closing since I'm betting this "ugly as fuck font" was the same as what happened in #688.
