### ISSUE TITLE
translate consecutive っ into a single one

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#421]
Consecutive っ indicates a stronger emphasis level than a single っ. words formed with these are not listed in dictionaries and is unable to be scanned.
By translating consecutive っ into a single one cases like (1) could be scanned, these are quite abundant on SNS and dialogues in fiction. imo this is relatively low risk and unlikely to cause unintended behaviors.

cases like (2) and (3) will require the deletion of っ under certain conditions. (for example when it occurs at the 2nd syllable of i-adjectives). these are out of scope of this issue.

(1) かっっっこい => かっこい
(2) かっわいい =>かわいい

(3) かたい
![image](https://user-images.githubusercontent.com/24824399/77765633-7e449900-7079-11ea-8ace-d326361991b7.png)
(https://static1.squarespace.com/static/57055a42ab48deae6cba15fd/t/5707ec58cf80a1640df4d8d4/1460137062627/emphatic-consonants-jipa.pdf)

**Comment by siikamiika** [comment]
This would be doable by extending what was added in https://github.com/FooSoft/yomichan/pull/181, but there would be some extra performance penalty for checking the previous character in addition to the current. Anyway, I wouldn't touch it yet because it would conflict with https://github.com/FooSoft/yomichan/pull/286.

**Comment by toasted-nutbread** [comment]
Proof of concept:
https://github.com/toasted-nutbread/yomichan/compare/master...collapse-small-tsu

**Comment by siikamiika** [comment]
@toasted-nutbread Forgot about that feature. Seems like a better place for this anyway because some dictionaries might have entries with more than one consecutive っ or ッ. Do you think the ZWNJ handling should be moved out of of `source.js` eventually? Currently it would be problematic because maximum scanning length is handled in `source.js` and ZWNJ counts as one.

**Comment by toasted-nutbread** [comment]
It's probably fine for now, though it could work in either location if text source maps are used.

If we want the ZWNJ to not count against the scanning length, that would have to be handled in source.js anyways in some form.

**Comment by siikamiika** [comment]
When I did #181 I tested Chrome on Docs and the length limitation got really noticeable. I think it would be optimal if `TextSource` was like a file that had `seek` (relative) and `read`, and ZWNJ and maybe even surrogate pairs were internal. The API is currently a bit confusing.

**Comment by toasted-nutbread** [comment]
Yeah, there should definitely be some changes at some point with regards to how ZWNJ characters are handled, but at some level it needs to be handled in the text scanning part. Effectively, whenever one of those characters are encountered, it just needs to not count against the current limit. We can also decide to move the code to ignore these characters into the translator as well and use source maps. I need to get back to #286 at some point, because I think I made some changes which made the code a bit cleaner.

Related, but there is a similar issue with the setting of converting romaji to kana and then translating that. For example, `chikara` is 4 more characters vs `ちから`, so longer compound words don't scan well. Spaces will also break up expressions. I didn't necessarily intend for this to be a fully comprehensive feature, but it's a good example of how the scan length has side effects on functionality other than ZWNJ.

**Comment by toasted-nutbread** [comment]
@Pintliz: see #440.

**Comment by toasted-nutbread** [comment]
For posterity, the source of the PDF in the opening post is https://aaron-braver.squarespace.com/research.
