### ISSUE TITLE
Dictionaries on Yomichan's readme/homepage & licensing

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#429]
Primarily addressed @FooSoft:

With the initial completion of #385, another task is determining how to make users aware of this dictionary. I am wondering how the dictionary file should be hosted (on foosoft.net like the others? or just a link the the repository that I made?), and if there are any special concerns about licensing or anything else. If it's decided that the files aren't to be hosted on foosoft's site, and links to github repository release pages are used instead, would it be good to have some sort of "Third party dictionaries" section that is separate from the others?

In terms of licensing, I have actually already embedded attribution information inside the generated database. In the index file, there is additional information for `author`, `url`, `description`, and `attribution`. Yomichan doesn't store or present this information yet, but that is one of my next tasks to implement.
https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary/blob/d8e7f181d04d0ed08f00de359b32dd5b9a0221bd/main.js#L142-L151
https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary/blob/d8e7f181d04d0ed08f00de359b32dd5b9a0221bd/attribution.txt

This also brings us back to #297 (and also #322). If this dictionary had attribution information included and Yomichan is updated to display this information on the settings page, would this be able to be included in the list of dictionaries?

**Comment by FooSoft** [comment]
Yup, makes sense for it to go on FooSoft.net, especially considering that you will want to have it in order to use all of the Yomichan features available. I will add it there along with a link to your generator script. 

I think the main thing will be to have proper attribution on the homepage, as that will be the actual point of distribution. I believe the main reason there is dictionary attribution in Yomichan right now is that back in the olden days, all the dictionary data was distributed inside the extension itself. If the extension is merely consuming data coming from elsewhere, I don't think there is a requirement that you have to display the associated copyright/attribution info, but IANAL. That being said, it would still be a good feature to help users find out more about the source data that is being used from inside of Yomichan.

**Comment by toasted-nutbread** [comment]
Sounds good. I'll work on making the few changes required to show the extra dictionary data fields and I'll comment on this thread again once completed.

**Comment by toasted-nutbread** [comment]
#433 has now been merged, which can show the additional dictionary metadata added to the pitch accents dictionary. There is one more PR open which should come before the next release, and that is #437, which addresses some error messages in the backend. #376 is up to date so far with the changes.

**Comment by FooSoft** [comment]
@toasted-nutbread the new pitch accent dictionary data is now up, and a new testing release that includes this capability is queued for approval.
