### ISSUE TITLE
"is fullscreen" profile condition (or special case)

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#432]
Due to the issue noted in https://github.com/FooSoft/yomichan/pull/417#issuecomment-600945163, showing iframe popups in the root frame has to be made conditional in order to make it work when the iframe is in fullscreen. It can be a special case for this option, but it could also be a separate profile condition if there's a use case for that.

Depends on https://github.com/FooSoft/yomichan/issues/431.

**Comment by toasted-nutbread** [comment]
May also be required for iframes inside of shadow DOMs. Test 4 in [test-document2.html](https://github.com/FooSoft/yomichan/blob/a4c7d243f4cddfc4e2b29132fe65fe07ff86bc36/test/data/html/test-document2.html) isn't positioned correctly. The fallback for both of these cases could be to just use the old method of having the popup inside the iframe, but this will add some complexity since the popup/proxy will have to handle both cases.
