### ISSUE TITLE
Kanjium dictionary import error

### ISSUE THREAD

**Issue by jstressman** [FooSoft/yomichan#451]
> Error: Dictionary has invalid data in 'term_meta_bank_1.json' for value 'dictionary[0][1]', validated against 'schema.additionalItems.items[1]': Invalid enum value

I've tried in both the stable and the testing version of Yomichan.

![2020-04-12 00 09 22 bcknnfebhefllbjhagijobjklocakpdm 90094754c145](https://user-images.githubusercontent.com/973348/79060975-18e7cf00-7c59-11ea-924a-db32fa1c7dc3.png)

Tried with the file downloaded from https://foosoft.net/projects/yomichan/dl/dict/kanjium_pitch_accents.zip as well as directly from https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary/releases/download/1.0.0/kanjium_pitch_accents.zip

Both gave the error.

**Comment by FooSoft** [comment]
Just checked, and testing version is still on 20.3.14.0. Even though I have uploaded the updated version, there is an approval process that can take a couple of days because some of the permissions that this extension uses. Try again in a couple of days, and hopefully by then the new version will already be approved for the store.

**Comment by jstressman** [comment]
Thanks for the reply. I'll keep an eye on it and try it again when it updates.

**Comment by jstressman** [comment]
The version on the Chrome Web Store updated. I installed that version and now everything is working correctly. Thanks!
