### ISSUE TITLE
Extension does not work in Firefox Preview

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#470]
[Firefox Preview](https://support.mozilla.org/en-US/products/firefox-preview), which seems to be a new version of Firefox for Android, is being rolled out and has currently replaced Firefox for Android Beta. Unfortunately, this means that Yomichan does not work on it, because it seems to only support a very limited subset of extensions. My existing installation does not work and shows the message:

> Firefox add-on technology is modernizing. These add-ons use frameworks that are not compatible with Firefox 75 & beyond.
> [Learn more](https://support.mozilla.org/en-US/kb/add-compatibility-firefox-preview)

It also seems that you can't install addons directly using an .xpi file anymore.

**Comment by siikamiika** [comment]
I was following the development more closely last year and tried an early build of Firefox Preview in December which was pretty much in the same situation as the one in Play store right now. I understood that full extension compatibility is planned although it currently only supports a small amount of them, but that message seems to contradict with my understanding. The new add-on technology is most likely https://github.com/FooSoft/yomichan/issues/455 so that's one more reason to start working on the incompatible parts.

> It also seems that you can't install addons directly using an .xpi file anymore.

I expect this to change, maybe it's business savvy to prevent access to half-finished products.

**Comment by toasted-nutbread** [comment]
Resolving for now as they are slowly working on adding support for extensions, albeit slowly.
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/
