### ISSUE TITLE
Invalid search - please check for typing mistakes

### ISSUE THREAD

**Issue by toasted-nutbread** [FooSoft/yomichan#475]
Originally commented on 1fea8a3a10a0548da9f29552a6c97a89311fb8ed by @kuntung:

![image](https://user-images.githubusercontent.com/50363248/80053871-8563a780-8550-11ea-9790-f06a3ed965c6.png)
![image](https://user-images.githubusercontent.com/50363248/80053893-91e80000-8550-11ea-9c99-04560eedf654.png)
Hi, I'm learning Japanese recently. And your Plugin 'Yomichan' is great for me to note some new words. But, there are some troubles when I use this plugin. As the above figures show, I always get the error notice when I add one word. I don't what's wrong with my setting (I had read your instruction many times...). Sorry for comment here, because I haven't found any addresses that I can mail to. Many thanks.

**Comment by toasted-nutbread** [comment]
@kuntung: what word are you getting the error for, and what dictionaries do you have installed?

**Comment by NickavGnaro** [comment]
I was having the same issue. In my case, the reason was because some of the field names did not line up exactly (punctuation and all) in the card template on anki itself. To fix it, make sure you get your template correct (or rename the fields according to the names your template uses).

Then just to make sure, go back to yomichan settings and choose a different note type and go back to the desired note type (this will just refresh yomichan's view the card) and then re-set it up and you should be good to go.

**Comment by toasted-nutbread** [comment]
@NickavGnaro Can you provide an example of what your fields/templates looked like when you got this error? I was able to reproduce the error in Anki using a contrived example, but I wasn't able to reproduce it using Yomichan directly.

**Comment by toasted-nutbread** [comment]
Closing for now, as there is no clear way to reproduce using Yomichan.
