### ISSUE TITLE
Unable to add term's tags to Anki w/ {tags} marker

### ISSUE THREAD

**Issue by aiueo97** [FooSoft/yomichan#538]
I'm able to add a term's tags to an Anki card via the `{glossary}` marker, as shown here: 
![blah1](https://user-images.githubusercontent.com/65163733/81550735-f395d000-9380-11ea-9b90-96923f1c1acd.png)

But I want to add just the tags to another field in my Anki card, preferrably using the `{tags}` marker. When I try using the `{tags}` marker, the field ends up blank.

I've tried updating the template to use `definitionTags` instead of `definition.tags` as it is used in the `glossar`/`glossary-single` inline template, but the field still ends up blank.

Is this a bug, or am I using the template incorrectly?

For reference, here is a gist of my current template: https://gist.github.com/aiueo97/229189d8bf05159fc32ad010380d5138

I'm using JMdict.

**Comment by siikamiika** [comment]
It seems to be an issue with the result grouping mode. When you set the mode to "split definitions to their own results", `{tags}` works. Otherwise it doesn't, presumably because it's not clear how to group the tags when they point to different definitions.

I think it's a bug because at least it should inform the user somehow that the marker is unsupported with the current result grouping mode. The implementation could also be changed to just merge all tags together and remove duplicates.
