### ISSUE TITLE
Modifier key condition not working on search page(20.5.22.0)

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#558]
Works on popups within search page but the main result doesn't respond to modifier keys

**Comment by siikamiika** [comment]
This is a known issue: https://github.com/FooSoft/yomichan/pull/487#issue-410869748

> Not sure what should be done with query parser. I was planning to add some profile identifier query parameter for search page, but that's already kind of supported by the URL RegExp condition as long as unknown parameters aren't removed when dynamically changing the URL. It has some discoverability issues, though. Probably not a concern for this PR, currently modifers are just ignored on the search page.

The problem is that changing the profile also affects the behavior of the text parsing part of the search page. If modifier keys should be supported on the search page, text parsing and results should use a different profile. That's not implemented yet.

Do you need to switch between different profiles on the search page with the same query, or could you have a separate search page open as a workaround that had a condition matching the URL? You could add something like `&profile=identifier` to the URL to activate the secondary profile.
