### ISSUE TITLE
Audio of the scanned reading in merged mode should be prioritized when generating anki note

### ISSUE THREAD

**Issue by Pintliz** [FooSoft/yomichan#559]
![image](https://user-images.githubusercontent.com/24824399/82758050-c7fdf580-9e16-11ea-9a7f-5819faa76ffa.png )

The scanned word is ひとところ, but the generated card has the audio of いっしょ.

yomichan seem to grab the audio of the first item by default, it would be great if the scanned reading could be prioritized.

**Comment by siikamiika** [comment]
Related: https://github.com/FooSoft/yomichan/issues/544

**Comment by siikamiika** [comment]
I'm also thinking that it could be useful to add audio for all the term/reading pairs in merged mode. The end result could look something similar to how it's in Yomichan with each pair separted with a 「、」and the play button on the right side.

I've thought of improving the context awareness in general so that "usually kana" and kana only terms are sorted on top when the scanned text is also kana or sorting the resulting term/reading pairs based on the scanned text, but never got to doing that. I'll create a new issue for that including a link to this.

**Comment by toasted-nutbread** [comment]
> I'm also thinking that it could be useful to add audio for all the term/reading pairs in merged mode. The end result could look something similar to how it's in Yomichan with each pair separted with a 「、」and the play button on the right side.

Keep in mind there is overhead for that. `に` is the common example, as it will often have about 20 results.

**Comment by siikamiika** [comment]
It could be a separate marker such as `{furigana-audio}` so that it doesn't come as a surprise. `{audio}` itself could behave like before but the results could be sorted so that the first one will match the scanned text. One issue with sorting though is that the unique key can change.
