### ISSUE TITLE
Inputs/Textboxes flicker while scanning with shift

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#56]
I believe these started in the last few weeks, but it's hard to know for sure. Here are a few examples:

1. Create an issue in GitHub and highlight some text in the textbox. Then hold shift and move the pointer around. You can see the highlighted words (and any underlined, misspelled words) flicker.
2. On jisho.org, type some kanji to scan in the search box. While scanning, move around over the kanji. You'll see duplicates of the kanji flicker.
3. Reply to a post in [WaniKani's Forum](https://community.wanikani.com/). When scanning and moving the pointer in the textbox, the banner that includes things like bold and italics buttons flickers. This may be hard for you to test unless you want to make an account (I don't think you can reply anonymously). If you fix the first two, I can verify this myself.

**Comment by seanblue** [comment]
Any information on this?

**Comment by FooSoft** [comment]
This is happening because Yomichan needs to create a temporary "impostor" object over text controls in order to be able to determine the position of the cursor (this is normally not possible for `input` and `textarea` controls in HTML). This temporary object  (in principle) has the same styling as the text element underneath it. In practice, it is not possible to extract all of the style of the text element to make the impostor object look exactly the same. As soon as Yomichan is able to grab the text it destroys the temporary object, causing a momentary flicker. 

It's interesting that you say that this has just started happening recently, since this is the way Yomichan has always worked. It is possible that some recent change has made the length of time that the impostor is visible (yes, it has to be visible in order to get information about text under the cursor), but I haven't had the chance to dig deeper into this yet.
