### ISSUE TITLE
[bug] Katakana lookup changed sentence

### ISSUE THREAD

**Issue by HelenFoster** [FooSoft/yomichan#58]
Looked up オオカミ.
Found 狼 (おおかみ) which has audio, and 狼 (オオカミ) which doesn't.
Added the first one to Anki (in kanji).
The cloze-body then had the word written in hiragana (instead of katakana).
(Yomichan 1.1.18)

**Comment by FooSoft** [comment]
So I understand what is happening here, but I am not sure what the proper fix is.

* The JPOD101 audio provider requires me to pass in a Kanji expression as well as a reading in order to obtain an MP3 file for the current word. It has one for the combination of 狼 + おおかみ but not 狼 + オオカミ. There isn't really anything I can do about that.
* When search for オオカミ, Yomichan searches for your original text string *as well* as the string converted to all Hiragana. This is primarily used for being able to look up things that are written in Katakana for emphasis only (things that would otherwise be written in Hiragana and/or Kanji). For example, this allows you to find things like カッコウイイ, which you would not otherwise be able to. In order to do this, Yomichan creates an alternate "source text" string, which it then proceeds to transform through deinflection, etc. When it comes time to compute the cloze, Yomichan has no idea that the original string was actually Katakana ... it has been working from a Hiragana string the entire time. I will need to think about this some more, but this is probably going to get closed as a no-fix, since it would be quite a bit of work to handle this exceptional case correctly.

**Comment by HelenFoster** [comment]
Couldn't you just store cloze-body in the same way that you're storing cloze-prefix and cloze-suffix? The sentence must be getting split into 3 parts before the word is converted to hiragana.

**Comment by HelenFoster** [comment]
This is actually very common when reading children's stories. They often have words in katakana that don't have any katakana dictionary entry.

**Comment by FooSoft** [comment]
It's in the works. I'll try to get around to it for the next release.
