### ISSUE TITLE
Dictionary Purged Itself on Some Update.

### ISSUE THREAD

**Issue by SecretArmy** [FooSoft/yomichan#590]
While I don't know the reason, probably due to either Chrome or yomichan itself updating to latest ver. from time to time the dictionary just purge itself. Is there a way to prevent this sudden purge? Since I use 6+ dictionaries, it took a while to install them all each time it auto purge. Since I have tons of free space, I doubt it was the problem.

**Comment by toasted-nutbread** [comment]
The only known reason why browsers would purge the database without user action is due to storage limits. The "Storage" section on the settings page will show some information about the usage and limits, as well as a "Persistent Storage" button which attempts to force persistent storage. A while back, we also added the `unlimitedStorage` permission, which was also an attempt to prevent Yomichan's database from being unexpectedly cleared.

Without a clear indication as to why the purge occurred, there's not really much action that can be done. The last remaining task related to database clearing that I had planned on doing was to implement a check to see if the database has been unexpectedly purged. This wouldn't prevent it from occurring, it would only be for detection.

Related: #100

**Comment by SecretArmy** [comment]
Well, since the Persistent Storage is uncheckable on chrome, also have 70 GB of free space. Re install all the dictionaries is the only way huh?, hope someday this problem is fixed.

**Comment by toasted-nutbread** [comment]
Yeah, I think the Persistent Storage works on Firefox to prevent data loss, but does nothing on Chrome. I have actually not run into the database purging issue on Chrome before, so I can't say what might have caused it. I agree it is annoying, and if there was a clear way to mitigate the problem, we would do so. The browser database system has historically caused a lot of issues because it acts in an unexpected manner, or doesn't behave consistently across browsers.
