### ISSUE TITLE
[feature request] Show pitch accent information

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#61]
It would be nice if you could find a resource to include pitch accent information for words. For example, [Weblio](http://www.weblio.jp/content/%E5%85%88%E7%94%9F) shows something like `[0]` and `[1]` to indicate which mora has the downstep. And [OJAD](http://www.gavo.t.u-tokyo.ac.jp/ojad/search/index/sortprefix:accent/narabi1:kata_asc/narabi2:accent_asc/narabi3:mola_asc/yure:visible/curve:invisible/details:invisible/limit:20/word:%E5%85%88%E7%94%9F) shows a bar above high pitch mora and the downstep if there is one.

**Weblio**:
![image](https://user-images.githubusercontent.com/5884067/27803132-f6ae53b4-5ff5-11e7-8ebe-d364f4d2737f.png)

**OJAD**:
![image](https://user-images.githubusercontent.com/5884067/27803141-039b46c2-5ff6-11e7-92ca-5eea14491bf4.png)

**Comment by seanblue** [comment]
Any thoughts on this?

**Comment by FooSoft** [comment]
This (along with frequency lists) is something I am definitely adding support for after I work out the details about how to store this information in the extension and where to source it from. If you have any recommendations for quality offline sources of pitch accent information it would help. I will not support online sources since it's brittle, slow, and errorprone.

**Comment by skliew** [comment]
I think the one in Rikaisama (http://rikaisama.sourceforge.net) is pretty good. It's stored in a SQLite database that is bundled with its installation.

**Comment by seanblue** [comment]
@FooSoft I wonder if you could contact [OJAD ](http://www.gavo.t.u-tokyo.ac.jp/ojad) and ask for their raw data. They have pitch accents for a significant number of words (probably just about everything), plus professionally recorded audio for many verbs and adjectives, plus their conjugations.

They have a mail to link on their homepage via the "Inquiries" button. Given that the data is from a university, they might be willing to give out the data since it's for a free, open source project.

**Comment by faneca** [comment]
Hi, I made a hack to make this (kinda) work, with some drawbacks (explained below), by using [Kanjium](https://github.com/mifunetoshiro/kanjium/)'s data ([this file](https://github.com/mifunetoshiro/kanjium/blob/master/data/source_files/raw/accents.txt), in particular).

I've written the following python3 script to make those data mock the `innocent_corpus` format. Just download the file linked above and put it in the same directory as this script before running it. The result should be similar to the zip file I'm attaching here: [kanjium_pitchaccent.zip](https://github.com/FooSoft/yomichan/files/2447394/kanjium_pitchaccent.zip) and which can be imported directly into Yomichan:
```python
#!/usr/bin/env python3
import csv
import json
import zipfile
import pathlib


# Function for writing json files exactly as we want them
#
def write_json(filename, data):
    with open(filename, "w", encoding="utf8") as f:
        json.dump(data, f, ensure_ascii=False)


# Read kanjium's pitch data from "accents.txt" (TSV),
# and modify it to match Yomichan's frequency-like meta
#
with open("accents.txt", "r") as f:
    data_in = list(csv.reader(f, delimiter="\t"))

# data = [[t, "pitch", ": ".join(rp)] for t, *rp in data_in]
data = [[t, "freq", ": ".join(rp)] for t, *rp in data_in]


# Write output data in chunks to respective files
#
stride = 10000
chunk_iterator = (data[pos:pos+stride] for pos in range(0, len(data), stride))

filenames = []
for n, chunk in enumerate(chunk_iterator):
    filename = "%s_bank_%d.json" % ("term_meta", n)
    filenames.append(filename)
    write_json(filename, chunk)


# Write the index
#
index_data = dict(title="Kanjium Pitch Accents", format=3, revision="pitch1")

filename = "index.json"
filenames.insert(0, filename)
write_json(filename, index_data)


# Create zip file
#
with zipfile.ZipFile("kanjium_pitchaccent.zip", "w", zipfile.ZIP_DEFLATED) as f:
    for filename in filenames:
        f.write(filename)

# Erase intermediate files
#
for filename in filenames:
    pathlib.Path(filename).unlink()
```
The most important line to understand what I'm doing is the one that reads (number 22, I think):
```python
data = [[t, "freq", ": ".join(rp)] for t, *rp in data_in]
```
(Note: that `*rp` captures both the "reading" and the "pitch accent" of each data point -respectively, the second and third fields- as a single unit -a tuple- to then use it in `": ".join(rp)`; more on this later)

As can be seen there, I "disguise" the pitch accent data as word frequency meta-information. The `"freq"` part will have to be changed to `"pitch"` if Yomichan starts supporting that kind of info in the future.

As for the `": ".join(rp)` on that line, what it does is put together the kana -indicating the pronunciation- with the pitch accent info (a comma separated list of possible pitch accents), both things separated by a colon and a space. I decided to do it this way because I needed to include the phonetic information somehow, as Yomichan, currently, doesn't support separate meta-info for each pronunciation, just for all the matching (kanjified) expressions (the "terms", in Yomichan's internal nomenclature). So the big caveat with this method is that you end up with listings like the following, since it's impossible, at present (unless I'm missing a better way to do it), to associate the pitch accents for the different pronunciations to their respective individual entries:

![yomichan](https://user-images.githubusercontent.com/1409227/46491289-9633b780-c80a-11e8-8ee5-9054aa01598f.png)
(pay attention to the fact that both entries share the (kanjified) expression, but are pronounced differently, and also to the inclusion of all the pitch accent tags in both of them)

**Comment by xerpi** [comment]
Hi, any updates on this? It would be really useful to have pitch accent information :)

**Comment by toasted-nutbread** [comment]
We've recently finished some updates to how dictionary data is generated, presented, and styled in the popup and on the search page, so it may be good for this to be revisited. Based on some of the comments above, it looks like there is some data available for pitch accent information, but I haven't checked out what the format is and if there would be any licensing issues. I will also have to make sure the data could be appropriately stored in / retrieved from the database to allow it to be presented correctly. Maybe this can be done with the existing tagging/metadata system, but I'll have to make sure this won't create conflicts or add lots of special cases.

**Comment by toasted-nutbread** [comment]
One thing that has come up as I work on this is how the results should be presented. I've seen several different methods of presenting pitch accent information:
* [0], [1], etc. to indicate the downstep mora (mentioned in main comment). [example 1](www.weblio.jp/content/%E5%85%88%E7%94%9F)
* Bar over high pitch, and an additional indication of the downstep (mentioned in the main comment). [example 1](www.gavo.t.u-tokyo.ac.jp/ojad/search/index/sortprefix:accent/narabi1:kata_asc/narabi2:accent_asc/narabi3:mola_asc/yure:visible/curve:invisible/details:invisible/limit:20/word:%E5%85%88%E7%94%9F), [example 2](http://www.gavo.t.u-tokyo.ac.jp/ojad/search/index/sortprefix:accent/narabi1:kata_asc/narabi2:accent_asc/narabi3:mola_asc/yure:visible/curve:invisible/details:invisible/limit:20/word:%E4%B8%AD%E5%9B%BD%E8%AA%9E)
* Visual pattern of dots with height based on tone. [example 1](https://github.com/birtles/rikaichamp/issues/48), [example 2](http://www.m-gakusei.com/index.php?%E6%97%A5%E6%9C%AC%E8%AA%9E%E3%81%AE%E7%99%BA%E9%9F%B3)
* H-L representation with additional markers for downsteps. [example 1](https://en.wikipedia.org/wiki/Japanese_pitch_accent#Binary_pitch)

Does anyone have opinions on what would be the best representation(s) to have?

**Comment by seanblue** [comment]
@toasted-nutbread FYI, the links for the examples on the first two bullets don't work.

Personally, I think each of the first three options works pretty well. I **strongly** dislike the fourth option. It's very verbose without adding any visual benefit.

I think which of the first three to go with depends on how compact you want the information to be. If you want it to be very compact, you could make it a tag at the top of a term (like `P` or `news` is now), like `Pitch [0]`, `Pitch [3]`, etc. This could be particularly beneficial, as sometimes a word has more than one accepted pitch accent, and sometimes (rarely I think) it can even differ by part of speech. The visuals options from bullets 2 and 3 are both nice for an "at a glance" understanding, but I'm not sure it's worth the extra space it would take up. I am currently using a dictionary for Yomichan that has a visual pitch accent component, and it unfortunately takes up a lot of vertical whitespace.

If you want a visual component, just keep in mind that in either case you need to account for the two character mora (e.g. じゅ) as well as the small っ specially. And in the visual dot version, you have to include the dot for the subsequent particle, which wouldn't be necessary in the bar version. Personally I don't think a visual component is necessary, but it's probably nice for beginners to pitch accent. So long as you think it's worth the extra space it would take up.

**Comment by toasted-nutbread** [comment]
> @toasted-nutbread FYI, the links for the examples on the first two bullets don't work.

Thanks, fixed them.

> If you want a visual component, just keep in mind that in either case you need to account for the two character mora (e.g. じゅ) as well as the small っ specially

This part is fairly easy, and I've already accounted for this. I believe the small っ also counts as a mora, so that shouldn't need any special handling.

Thanks for the feedback. I'll experiment a little with some different visual presentation methods and likely add an option to control what is displayed.

**Comment by toasted-nutbread** [comment]
So far, these are the styles I have added. The tags in the images below are currently showing all options simultaneously. This will not be the default when this feature is fully implemented, this is only for demonstration purposes. The images also demonstrate how accents can differ based on part of speech, as @seanblue mentioned.

1x scale:
![image](https://user-images.githubusercontent.com/11037431/74118100-00d7ce80-4b88-11ea-86c5-2f0daf499983.png)

2x scale:
![image](https://user-images.githubusercontent.com/11037431/74118106-0503ec00-4b88-11ea-9442-40bf1126ef17.png)

**Comment by seanblue** [comment]
Is the plan to release this bundled with an existing dictionary or as a standalone dictionary?

**Comment by toasted-nutbread** [comment]
It will be treated as a standalone auxiliary dictionary.

**Comment by toasted-nutbread** [comment]
Commenting on pitch-accent-related stuff from https://github.com/FooSoft/yomichan/issues/354#issuecomment-584872975 in here, just to try to keep relevant discussion in this thread:

---

> The pitch accent data you used in #61 seems to have part of speech, which I assume you got from the Rikaisama sqlite

I'm using the data from https://github.com/mifunetoshiro/kanjium/blob/master/data/source_files/raw/accents.txt, but it's probably from the same source.

The part-of-speech notation is cosmetic and doesn't necessarily correlate with other dictionaries. They are converted from the Japanese abbreviations to English abbreviations that match the tags in JMdict, but this conversion isn't used for any other purpose. And out of the ~120,000 terms listed in the source, only ~400 have these annotations.

> that can't be directly mapped to expressions at least in the format that JMdict uses

In this case, they are handled much the same as the existing frequencies, and there may be similar issues as you mentioned. A question could be: what is the ratio of correct, incorrect, and unused data for freq/pitch entries?

I haven't validated the pitch accent approach much beyond some initial testing so far, since it's based on how frequencies are treated. I'll do some more testing and eventually put up a PR to see how well it works in the general case.

**Comment by seanblue** [comment]
> I'm using the data from https://github.com/mifunetoshiro/kanjium/blob/master/data/source_files/raw/accents.txt, but it's probably from the same source.

This might seem like an odd request, but I'd recommend stripping out the entries that are entirely English characters. Based on my experience with another pitch accent dictionary, this could unfortunately result in scanning basically any English text on the page when you try to scan for Japanese text. Maybe it would be fine since they appear to be the full width variants, but I'd at least test for that.

**Comment by toasted-nutbread** [comment]
See: #385

**Comment by toasted-nutbread** [comment]
#385 has now been merged. There are a few more changes to make before it gets into a release, but the feature should be available soon.
