### ISSUE TITLE
[feature request] Close popup when scanning returns no results

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#71]
As a former rikaichan user, I liked being able to move mouse around to quickly peek words on a webpage. With Yomichan, this becomes difficult because you have to close the popup with `Esc` or by clicking somewhere to see what's under the popup.

In the default mode, Yomichan only scans when you hold `Shift` down. In my opinion, closing the popup when `Shift` is held down and you move mouse outside a word wouldn't be a problem. But if you set scan modifier key to `None`, it can become a problem.

I would really appreciate if this feature could be added as a checkbox under Scanning Options. Thank you!

Edit: example use case where this is very important: YouTube subtitles

**Comment by non-e-moose** [comment]
This would be indispensable for beginners.
Now we have to either click shift all the time or click the mouse/Esc all the time.
It's really annoying.
Just add it as an opt-in option within the advanced settings if you think most users wouldn't be interested.

Could the developer at least address the issue? I see you commented on a newer issue already but are ignoring this one for some reason. (Don't take it as an attack, I just really want to know if it is going to get implemented, or if I will be forced to go back to ESR and Rikaisama.)

**Comment by FooSoft** [comment]
@non-e-moose 

The "developer" maintains this project entirely during his free time and basically gets nothing for it. If you divide the amount of donations I've received by the number of hours I have in the projects, you would see that I'm "working" for pennies on the hour. It is a purely labor of love that has had hundreds of hours poured into it, arguably at the expense of time which I could have used to study Japanese myself. 

If you ask nicely (which most people do), I feel motivated to get things done because I genuinely want to help them. Look at the huge list of resolved issues to see examples of this for yourself.  The amount of time to get to an issue varies on implementation details, how busy I am at work or with my family (I just had a son two weeks ago), or simply if it is something that I want to work on at a given time. I reply on issues when I need additional information or when the reporting user is someone I recognize as part of the Yomichan community who has been actively contributing to its development through bug reports or suggestions for some time. If an issue is listed here, it means it is something I intend to do (I close issues which I don't find useful). 

Downvoting an extension you got for free and then jumping in and asking "why is feature X not done yet" is not a way to get any open-source developer (not just me) excited about helping you. Yomichan is not a product, you are not a customer, and I am not your service representative. You are not any more entitled to get developer time on a freeware software project than a guy with a dead car battery is to get a jump start from a stranger. Writing code requires actual time; if you want instant changes, feel free to open a pull request or use a different extension.

**Comment by non-e-moose** [comment]
I don't understand what got you so angry. I guess the fact that I bumped the issue so shortly after the other guy opened it? I just got excited and wanted to know if you are even considering it, I wasn't demanding resolving it immediately or anything, I even wrote a disclaimer about it.

Also, is 'developer' a bad word to use for open source? Does it imply monetary gain or something? I though it just meant 'the guy that develops something'. What word should be used instead? Also, is bumping an issue really considered a 'downvote' on github? I guess I should learn more about the site culture before posting.

**Comment by FooSoft** [comment]
@non-e-moose some guy voted the extension to one star on the Firefox portal today at nearly the same time you filed the issue, and he had very similar wording to your post. I apologize if that was not you. It is just disappointing when you are trying to get an extension out there and every vote counts. Feel free to ignore the now apparently misdirected rant; it was influenced by a mistaken assumption.

But yes, this issue will be addressed, probably in the next release or one after that. I have been busy adding support for frequency tables.

**Comment by siikamiika** [comment]
@FooSoft Thank you for the update! I was afraid of touching anything because I'm not familiar with the code, but when testing 9280985306f5a9c79b9bd2c4daea596a5ec78ae5, I saw that it only closed the popup when there was text that doesn't return results but not when moving mouse outside the text.

After doing the following changes, the functionality was close to what I wanted but not quite:

```diff
diff --git a/ext/fg/js/frontend.js b/ext/fg/js/frontend.js
index e403528..a446f5b 100644
--- a/ext/fg/js/frontend.js
+++ b/ext/fg/js/frontend.js
@@ -181,9 +181,13 @@ class Frontend {
                 return;
             }
 
-            if (textSource && textSource.containsPoint(point)) {
-                this.pendingLookup = true;
-                hideResults = !await this.searchTerms(textSource) && !await this.searchKanji(textSource);
+            if (textSource) {
+                if (textSource.containsPoint(point)) {
+                    this.pendingLookup = true;
+                    hideResults = !await this.searchTerms(textSource) && !await this.searchKanji(textSource);
+                } else {
+                    hideResults = true;
+                }
             }
         } catch (e) {
             if (window.yomichan_orphaned) {
@@ -197,7 +201,7 @@ class Frontend {
             docImposterDestroy();
 
             if (hideResults && this.options.scanning.autoHideResults) {
-                this.popup.hide();
+                this.searchClear();
             }
 
             this.pendingLookup = false;
```

For some reason, moving the mouse left of an element containing text like a `<h1>` or `<td>` doesn't close the popup but moving up, down or right does. I want to contribute to this feature but I'm afraid there's something I'm missing about how the detection of text under mouse cursor works.

I see that @non-e-moose also needed this feature and commented, but I just want to say that @FooSoft has been really active responding to all the bug reports and feature requests compared to many other open source projects out there. This feature request wants to change something very critical about how the extension works and I understand that it should be done properly. Please be patient!

**Comment by non-e-moose** [comment]
@siikamiika Yeah I got too excited and too pushy, it's just that it's the most important extension for me (even more important than uBlock and uMatrix combined).

**Comment by FooSoft** [comment]
@siikamiika I've made some more code changes, I think this is closer to the desired behavior. Let me know if you see any undesired behavior.

**Comment by siikamiika** [comment]
@FooSoft The popup hiding is perfect now, thanks!

(The following is just some ideas that should probably be formatted to a new feature request or be put on my own TODO list.)

The only thing my workflow seems to lack after setting `General Options → Popup offset` to `0` and `Scanning Options → Scan modifier key` to `None` is rebinding toggle on/off from `Alt+Delete` to something available with the left hand, such as `F1`, but seems like it's hardcoded to `manifest.json` so I don't think you can configure it after compilation. It's also fairly rarely needed so reaching `Delete` once in a while isn't that bad.

Otherwise, the interactive popup works surprisingly well even without a scanning modifier key. Allowing the user to configure the X position of the popup (move it a bit to the left) would probably eliminate most of the cases when you accidentally close the popup by moving mouse cursor a bit too much to the left when attempting to scroll the popup results or click the kanji. Also, the [Amazon menu hack](http://bjk5.com/post/44698559168/breaking-down-amazons-mega-dropdown) comes to my mind: moving the mouse to the right can cause Yomichan to look up some other word next to the one that is wanted. But as said, this is just me throwing some ideas around.

Below is a recording of me testing it:
![peek 2017-09-18 02-30](https://user-images.githubusercontent.com/5602483/30525920-5fc3ddce-9c19-11e7-82fb-e288984a6188.gif)

**Comment by FooSoft** [comment]
Sweet, then this feature will be in the next release. Regarding the problem you are having of accidentally looking up words when trying to move mouse to popup window, you could try setting the popup delay vlue to 20 or 25 ms. It is the delay after mouse stops moving to search under cursor.

**Comment by FooSoft** [comment]
Also, your fonts look kind of messed up, what OS are you running?

**Comment by siikamiika** [comment]
Yeah, I'll try to find a sweet spot for the popup delay. It's just that the longer it is, the less snappy the usage will feel, but the current state is very usable when you get used to it.

I'm using Arch Linux (Firefox) and the Japanese font is Source Han Sans. It could be just blurry because of scaling, try clicking the gif and it will be sharper. I personally like the font.

**Comment by FooSoft** [comment]
Nice, a fellow Linux user :+1: 
I run Fedora myself (former Arch user).

The font issues I'm talking about are the alignment of the text inside the tags. Here is what it should look like: ![screenshot_2017-09-17_18-30-47](https://user-images.githubusercontent.com/544478/30526847-849b2c26-9bd6-11e7-825c-5a2ae2d9dbd9.png)

Anyway, it's something that can be fixed by installing the Microsoft core fonts package.

**Comment by siikamiika** [comment]
It was the Nimbus font family again... I have already blacklisted some of them before (they come with a dependency) but this one wasn't for some reason. Now it falls back to Arimo which is metric compatible with Windows Arial.

![](https://eddykk.com/ss/miika/2017-09-18_04-47-12.png)

**Comment by FooSoft** [comment]
Nice, that looks better :+1:
