### ISSUE TITLE
Yomichan doesn't work in web accessible resources of other extensions

### ISSUE THREAD

**Issue by finnp** [FooSoft/yomichan#711]
I have an extension that injects an iframe with a web accessible resource HTML. Yomichan does not work within that iframe. But furthermore if I open the iframe in another tab, it also doesn't work.

I wonder if there is some security setting that prevents this?

Here's a screenshot of a page that doesn't work with yomichan:
![image](https://user-images.githubusercontent.com/841788/89132647-f6363a80-d515-11ea-9996-95711fb34ffb.png)

**Comment by finnp** [comment]
Maybe this could be fixed by allowing `chrome-extension://` here:

![image](https://user-images.githubusercontent.com/841788/89132707-6e046500-d516-11ea-85ca-c7eba8efdc53.png)

**Comment by toasted-nutbread** [comment]
> Maybe this could be fixed by allowing `chrome-extension://` in the `manifest.json` here:

I don't think this would work, since different browsers use different prefixes.

I think in general, Web Extensions aren't able to run on other Web Extension resources. There is an alternative that would work, however: you could inject the content into a blank iframe, either by using [`srcdoc`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/srcdoc), or by directly modifying the document's content via `iframeElement.contentDocument.documentElement.innerHTML = ...` or similar. These are effectively treated as `about:blank` URLs, which Yomichan does run on.

**Comment by finnp** [comment]
Yeah, I just found out that chrome doesn't allow this: https://stackoverflow.com/questions/10196258/does-content-scripts-matches-chrome-extension-work.

Thank you for the suggestions! I will try it out.

**Comment by toasted-nutbread** [comment]
Another alternative could be to just set up a dummy webpage that your extension would take control of, which could be as simple as a blank Github Pages page. This would have more security than an `about:blank` frame, in case that is a point of concern for you. There may be bandwidth concerns with using a real webpage, but that could also be worked around by getting the extension to intercept requests to that URL and serve your own.

**Comment by finnp** [comment]
Yeah, good point. I got it working with your suggestion and message passing between the content script and the iframe and for now it's fine security-wise.

Thanks again for the help.
