### ISSUE TITLE
Yomichan with Bibi Epub Reader on Chrome

### ISSUE THREAD

**Issue by akuma-no-meido** [FooSoft/yomichan#755]
This is a web-based epub reader: https://github.com/satorumurmur/bibi
Yomichan seems to work fine on it using Firefox but not on any Chrome based browsers that I tried. Could it be an issue with Yomichan?

**Comment by toasted-nutbread** [comment]
Do you know of an example file that I could test with?

**Comment by akuma-no-meido** [comment]
> Do you know of an example file that I could test with?

[kinkakuji.zip](https://github.com/FooSoft/yomichan/files/5120601/kinkakuji.zip)

**Comment by toasted-nutbread** [comment]
So the bibi app works by embedding content in an `iframe` element with a URL of `blob:http://localhost:12345/AAAAAAAA-AAAA-AAAA-AAAA-AAAAAAAAAAAA`. Firefox will inject the extension into this frame, presumably because it acts similar to an `about:blank` URL, which Yomichan does get injected into. However, Chromium browsers don't appear to do this, resulting in the extension not being run in the nested frame. This is why the extension does not run on those browsers.

I can add a manual test for this setup in case this behaviour changes in the future, but I doubt the issue can be fixed on Yomichan's side, since the issue is with the web browser.

**Comment by akuma-no-meido** [comment]
Alright thank you. It's not a big issue as I can use Firefox for reading, still thank you for checking. As it's not a Yomichan problem I will close this issue. I'm also going to delete the epub I posted as I mistakenly assumed that book was in the public domain.

**Comment by toasted-nutbread** [comment]
It's an interesting case that I hadn't considered before, so thanks for bringing it to our attention. I've added a simple test case in #757 for internal testing purposes based on this report. As expected, it works in Firefox but not in Chrome.
