### ISSUE TITLE
[bug] Error in importing dictionaries

### ISSUE THREAD

**Issue by Mishrito** [FooSoft/yomichan#81]
Trying to import a zip dictionary file gives the error message

Error: OpenFailedError: InvalidStateError A mutation operation was attempted on a database that did not allow mutations

Windows 7 64bit
Firefox 55.0.3 64bit

Yomichan works perfectly on Chrome. I get this error only on firefox. I had tried using it on firefox a couple months ago and it had given me the same error back then too.

**Comment by FooSoft** [comment]
Thanks for the report. Yomichan heavily uses IndexedDb, an API for persistent storage in order to load and search dictionaries. The problem is that the Firefox implementation of this system is very buggy. Could you please try the following things (in this order, verifying if the problem is fixed after each one).

* Make sure you have plenty of space available on your system drive (Firefox will only use up to 10% of remaining space).
* Delete the following directory in your profile:  `firefox/ko3hmd6d.default-.../storage/default/moz-extension...`
* Perform a [Firefox refresh](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings?redirectlocale=en-US&redirectslug=reset-firefox-easily-fix-most-problems)

**Comment by Mishrito** [comment]
I did do a refresh. However it seems setting Firefox to "Never remember history" in the Privacy settings is causing the issue; switching back to remembering history makes it functional again (I only thought of trying this after the refresh though). If firefox is set to remember history, Yomichan works even in a Private Window.

**Comment by FooSoft** [comment]
What the hell that is the most bizzare thing I've ever heard of about Firefox. So you can basically reproduce this issue at will just by toggling that option? I will have to try it once I get home. Thank you for the detective work, this will be extremely useful in helping troubleshoot problems that other Firefox users experience. I can only guess that Firefox implements "Never remember history" by preventing write access to IndexedDb. Pretty stupid.

**Comment by Mishrito** [comment]
Yep, everytime I set "Never remember history" it shows the same error, and turning "remember history" back on makes Yomichan work again. 

And like I said before, Yomichan works in Private mode, which is weird because I thought the "Never remember History" option is like a permanent private mode, but apparently it's not exactly the same.

**Comment by FooSoft** [comment]
I now catch this exception and notify the user about this as being a possible cause. Unfortunately, there is not much else that can be done from inside the extension.
