### ISSUE TITLE
Update JMdict builds at https://foosoft.net/projects/yomichan/index.html#dictionaries

### ISSUE THREAD

**Issue by Thermospore** [FooSoft/yomichan#834]
Seems the JMdict builds here are a few years out of date (the English one at least). Would be great to see them updated with more recent ones! Thanks! -Tyler

**Comment by toasted-nutbread** [comment]
Probably more of a task for @FooSoft, since I am not sure how the dictionaries were generated initially. But in the case that @FooSoft is able to update them (or give instructions), there is some additional metadata that would be nice to add to the file. It's documented here:
https://github.com/FooSoft/yomichan/blob/master/ext/bg/data/dictionary-index-schema.json#L33-L48
This is the info I added to the [pitch accent dictionary](https://github.com/toasted-nutbread/yomichan-pitch-accent-dictionary).

**Comment by FooSoft** [comment]
Should be pretty easy, just use [Yomichan Import](https://foosoft.net/projects/yomichan-import/), and give it the JMdict XML file; it will be able to create a converted dictionary. I'll need to update this tool to include this new metadata at some point...

**Comment by Thermospore** [comment]
> the JMdict XML file

Wow, I'm embarrassed to admit I tried using Yomichan Import to do it a few weeks ago but didn't realize the `.gz` from the JMdict website was a compressed file...

Here is the import I made for myself, if anyone wants it. I looked at the additional metadata but I wasn't confident exactly what you had in mind, so I only added the URL. Very exciting to have this up to date, thanks for the info!

[jmdict_english_sep2020.zip](https://github.com/FooSoft/yomichan/files/5259528/jmdict_english_sep2020.zip)

**Comment by Thermospore** [comment]
Including the additional metadata, as @toasted-nutbread mentions, it would also be nice to include notes and cross-references in the import as well! Not all, but many of the notes are very valuable information.

For reference, by "notes" I'm specifically referring to the info contained in `《 》` brackets. Like on this entry for example: http://www.edrdg.org/jmdictdb/cgi-bin/entr.py?svc=jmdict&sid=&e=2077291
