### ISSUE TITLE
Merging tags

### ISSUE THREAD

**Issue by non-e-moose** [FooSoft/yomichan#85]
I think  that the following pic illustrates pretty well why the current handling of tags isn't optimal
![firefox_2017-09-28_01-13-40](https://user-images.githubusercontent.com/32024635/30942273-54e87aee-a3ea-11e7-9d39-edf2ff50fa93.jpg)
I think adding the tag line only if it's actually needed would be better.
Something like
![ver_2](https://user-images.githubusercontent.com/32024635/30942362-e8bd8a0c-a3ea-11e7-92a1-edc05dcb686b.jpg)
wastes less space and is more readable (you are less assaulted by information and colors) than
![firefox_2017-09-28_00-59-40](https://user-images.githubusercontent.com/32024635/30942177-a0881744-a3e9-11e7-9f18-91ba5c45b87b.jpg)
Sorry for my poor graphic editor attempt at showing what I mean, I hope it's still understandable.

**Comment by FooSoft** [comment]
May make sense to combine this with #84

**Comment by non-e-moose** [comment]
I weren't sure if it was similar enough to write it in that thread, sorry.

**Comment by FooSoft** [comment]
It's kind of a different idea, but at the point that there is effort made to fix grouping, might as well do it all in one go.

**Comment by FooSoft** [comment]
(really, it's just me being sneaky and trying to get @siikamiika to do more work, lol)

**Comment by siikamiika** [comment]
@FooSoft Actually, I have an idea about this :smile:

Again using how my own project handles this as an example because it's pretty much raw JMdict:
![2017-09-28_02-58-16](https://user-images.githubusercontent.com/5602483/30943319-ec22c4a6-a3f8-11e7-8890-a0fd42c3ed6d.png)

JMdict associates the frequency information (`spec` label) with a specific reading within that group, but the group for の happens to have only one reading. Common words are indicated with red color and you can see why it's common if you hover mouse over it. The part of speech `prt` (particle) is only for the first _sense_ (numbered thing), and not for the rest.

Also, there are some additional bits of information for some senses that can be important for understanding them, such as 最早:
![2017-09-28_03-05-54](https://user-images.githubusercontent.com/5602483/30943498-fe755ece-a3f9-11e7-8fd1-c900d781fc04.png)

**Comment by FooSoft** [comment]
That looks pretty slick. Honestly, my knowledge of JMdict is pretty limited and can be mostly attributed to trying to get basic information out of it but not digging too much deeper. Even what's in there know is mostly a result of users bugging me to use the format properly, lol.

**Comment by non-e-moose** [comment]
@siikamiika 
I really like the template, the additional comments seem very useful and the simplicity is a big plus, though honestly I don't understand the significance of the question marks.

@FooSoft
I just thought about another thing and I'm not sure if it's worth opening a new issue, how would you feel about using semicolons instead of the bullet points? I love that the numbered list has line breaks (I really hated how jumbled Rikaisama was, they didn't use any line breaks at all within the definitions), but I don't think that the line breaks between bullet points are needed, semicolons should work just as well. I think it would save some scrolling while still keeping things perfectly readable. What do you think?

**Comment by siikamiika** [comment]
The small superscript question mark indicates that there is an explanation for the abbreviation if you hover your mouse above it. I think I got the inspiration from Wikipedia or something similar.

**Comment by non-e-moose** [comment]
I understand now. Though to be honest I prefer FooSoft's approach to this, it's cleaner.

**Comment by mattdeckard** [comment]
Is this being worked right now? I've been wanting to contribute to this project and think I'm going to have some time this week but I don't want to step on anyone's toes.

**Comment by siikamiika** [comment]
@mattdeckard The feature was implemented in 8d660e282911ffb5d7b504784a3c09f13b164953, but it has to be enabled separately from options. In General Options, there is a checkbox called "Compact tags".

@non-e-moose @FooSoft this issue can be closed.
