### ISSUE TITLE
[feature request] Add way to update dictionary

### ISSUE THREAD

**Issue by seanblue** [FooSoft/yomichan#86]
As far as I can tell, there is no way to update a dictionary without purging and reimporting all dictionaries. Specifically I wanted to reimport `kanjidic_english.zip` since you added some new sections on the kanji popover but they all say `No data found` (I assume this new data is in the new version of the dictionary, but please correct me if that's wrong). When I tried to import the new version of `kanjidic_english.zip` I just got the error `Dictionary is already imported`.

If I'm misunderstanding something, please let me know. Otherwise, I think allowing a reimport/overwrite of an existing dictionary would be useful.

**Comment by seanblue** [comment]
I just remembered to check your website and saw that there was an explanation in your FAQ. It's unfortunate if the entire database needs to be purged, but I'm curious about the technical reasons if you don't mind giving a short explanation.

**Comment by FooSoft** [comment]
Sure.

It all comes down to IndexedDB being garbage. Adding rows to the database is slow (hence the need for the progress bar), but it is manageable. Deleting rows (as I found out after implementing a nice UI for deleting dictionaries) is an operation that is riddled with problems. It can take up to 10 minutes to drop a couple hundred thousand rows during which the extension becomes unusable (since IndexedDB is busy). The drop operation can randomly corrupt your Chrome profile and even somehow completely destroy query speed on the remaining rows. Back when I tried this, there was no Firefox port yet, but considering that IndexedDB sucks even more in Firefox, it's not even worth testing it. From my experience, shipping a broken feature gets users more upset at you than not having the feature at all, so that's why all you have is "purge". At least that works quickly, right?

Yomichan pushes IndexedDB a lot harder than other web applications, and thus runs into all of these problems. I wish that there was an alternative (for example Rikaichan for Firefox used SQLite directly), but for WebExtensions, IndexedDB is your only option for persistent option for storing data (yes, JMdict won't fit in a cookie, lol).

**Comment by seanblue** [comment]
Are you using WebExtensions for cross browser compatibility?

The purge is quick, but I remember one of the dictionaries taking a while to import, which is why I like to avoid it. Have you considered some type of versioning system? Basically something that allows you ("you" being you or anyone else that creates one of those zip dictionaries) to increment a dictionary version so it can be imported as a new one and the old one can be disabled. I guess that would hurt performance, unless you are ignoring disabled dictionaries in some way that makes it a non-issue.

**Comment by FooSoft** [comment]
WebExtensions are the only way forward for extensions nowadays. Firefox is deprecating their old extension model, and the vast majority of extensions for that browser will not function when Firefox 57 is released (I think in November). This means that even the extension that Yomichan was inspired by (Rikaichan) will cease to function.

There is currently a versioning system in place, and that is why you are able to even view Kanji definitions even though you have the old version of the data. It simply can't display the additional information since it's just not present. You could technically just open up the dictionary ZIP file, change the name stored inside in the index file to something other than KANJIDIC (English), and then Yomichan would allow you to import it. You could then disable the old version.

I'm hoping that changes like this are going to be very infrequent as they are kind of pain in the ass from both the user and development standpoints.

**Comment by FooSoft** [comment]
I'll run a test this weekend to see if anything has changed in terms of row deletion performance. Not holding my breath though.

**Comment by seanblue** [comment]
Since I never heard back from you, I decided to just update my dictionary by purging and reimporting. I have two recommendations based on doing this:
1. When clicking the purge link, you should confirm that the user actually wants to purge the database. I was really surprised when it just _started_.
2. The new kanji information is kind of overwhelming, and mostly unnecessary (for me). It would be nice if you add a setting to not display the separate sections (`Classifications`, `Codepoints` and `Dictionary Indices`).

I can create separate issues for these if you prefer.

**Comment by toasted-nutbread** [comment]
Support for deleting a single dictionary has been added in #272. For 1. and 2. in https://github.com/FooSoft/yomichan/issues/86#issuecomment-338803852, if these are still issues that are relevant to you, please feel free to open new issues to track them.
