### ISSUE TITLE
[feature request] Fail cards from popup

### ISSUE THREAD

**Issue by gajewsk2** [FooSoft/yomichan#9]
Starting this tomorrow and would like some feedback. 

Firstly, I would like to make this feature compatible with both sentence and vocab cards. I'm thinking I will have to add a checkbox to chrome settings, which will look for the vocab word _anywhere_ in the Reading field. If so it will treat the card as existing, enabling a red X for that vocab entry in the dictionary popup. As you can imagine you might have multiple cards with that vocab word, so multiple cards could be failed that match the Kanji and Kana in the cards Reading. Can I enforce that the user must have a field Reading to use this feature? Or do I need to allow the user to specify a field name from a dropdown of available fields? 

Approach:
1. Setup trigger to send fail message on a new red X icon, which will be to the right of the smallest plus for each entry. X will be grayed out if the card does not exist, but will still be present. X will turn red when card exists.
2. In AnkiConnect, mark the matching card as due today, return success if card was found and successfully marked.
3. Give some sort of user feedback on how many cards were failed. Would like some idea how to approach feedback. Small popup in the bottom right hand corner that shows a list of Expressions failed, and then fades out after half a sec?

Can I release this in just Chrome to start?

**Comment by FooSoft** [comment]
Couple of things:

* You mention *sentence* and *vocab* cards. Currently there are only two types of cards: *vocab* and *kanji*... where do *sentence* cards come in?
* You should not do the whole reading searching thing as that makes additional requirements for what the user must do. Just look at the code that determines whether or not to show the `vocab_kanji` and `vocab_kana` buttons. That already works as a way to determine if a corresponding card exists. It basically tries to create a card and sees if it's addable to the deck. You should download the source code for Anki and dig around in it until you find out how the determination is made that a card cannot be added, replicate that behavior to find the correct node and set the expiration time on it. 
* Having the extension call into AnkiConnect, waiting for a `true` / `false` response and displaying a message box on error sounds like a good way to do error handling. I already do this for note creation.
* Is feedback about how many cards were failed necessary? You should be able to look in Anki and see how many cards are now marked as "due" to get an idea. When you press the "fail" button, the button should gray out as soon as the operation completes to indicate to the user that their action did something. Cards that are already due should not be re-failable because that would just be dumb (check the due date on the card before determining if it can be failed). 

Some other thoughts:
* All code should be using ES6. Crufty ES5 code is not allowed. Match the surrounding code style as much as possible (`===` instead of `==`, etc). 
* Use the [FamFamFam Silk Icon Set](http://www.famfamfam.com/) for any additional icons you want to introduce.
* Break things into small, logical pull requests.

Releasing on Chrome only is fine as long as you make the required changes to AnkiConnect in both the standalone AnkiConnect plugin and the Yomichan plugin.

**Comment by gajewsk2** [comment]
> You mention sentence and vocab cards. Currently there are only two types of cards: vocab and kanji... where do sentence cards come in?

- Right, could we add sentences as well? I only use sentence decks, so I'd like this feature to work with sentences as well as vocab. Maybe a separate tab would be more appropriate? I'm guessing I would need to make a separate feature request for that?

- I would prefer some sort of user feedback at some stage for this feature. I'm thinking the user could have multiple cards that match, but again maybe I'm thinking of sentences too much, and should just start with vocab.

I managed to run the template and dict .sh scripts , but for some reason I get 
`extensions::messaging:342 Uncaught TypeError: 
Cannot read property 'name' of undefinedsendMessageImpl @ extensions::messaging:342(anonymous function) @ VM1605 extensions::runtime:115target.(anonymous function) @ extensions::SafeBuiltins:19(anonymous function) @ VM1606 extensions::binding:59target.(anonymous function) @ extensions::SafeBuiltins:19(anonymous function) @ VM1606 extensions::binding:422bgSendMessage @ api.js:21bgFindTerm @ api.js:25searchAt @ client.js:102onMouseMove @ client.js:57`

**Comment by FooSoft** [comment]
Sentences would be definitely nice to have (the only reason they are not in right now is because navigating range objects is kind of a pain in the ass), but I see that as just being a `{sentence}` tag that gets filled on vocab cards (so it would not be a new "type" of card, just a new thing you can add to the template, just like how it works in Yomichan for Anki). Why do you figure it would need to be something new? In either case, yes, this would be a separate "task" that would have its own pull request. 

As for feedback, I generally agree that it is good, but I am just trying to understand your reasoning here. We currently don't have any feedback about how many cards were added, so why would we have feedback about how many cards were failed? Trying to avoid inconsistency. If you are set on doing this,  it should probably be done in both places. As far as the notification mechanic goes, maybe some sort of popup on the browser action button (haven't looked at the API enough to know if this is possible). Doing a popup at bottom of page is good in principle, but it would require creating more IFRAMEs since that's the only real way to make sure page styles don't screw around with our own styles.

Task runner could potentially be nice, but the ones I've used so far were really based around working in a single ecosystem (like all JavaScript). I like to use different tools for different things (will probably be migrating the dictionary compiler to Go in the near future. If it's possible to make NPM do things like install Go tools, maybe that would be a nice thing to have.

Finally, the error you are getting is what happens when you install or update the extension but the injected content script is out of sync with the background script. See if just reloading the page fixes the issue for you.

**Comment by gajewsk2** [comment]
Cool, I agree with those points, I'll give you my thoughts when I dig into the code a bit more. I did get it past that error by removing the original yomichan ext, they both were loading at the same time for some reason. Now it just never returns the definition for chrome.runtime.sendMessage({action, params}, callback); when the action is findTerm. The length for that callback is always zero. Is there some trick for connecting the dict?

**Comment by FooSoft** [comment]
There is no trick really, maybe your dictionaries aren't properly generated? Did you clone the submodules and do you have GIT LFS installed? You should have a 38mb `ext/bg/data/edict.json` file (along with some other files in that directory). You should see if you are getting any errors in the background script.

**Comment by gajewsk2** [comment]
Yup that was it. It's working now; never used git-lfs very cool.

**Comment by FooSoft** [comment]
I'm not sure what you mean about reconnecting since the extension does not maintain a persistent connection to Anki (it's just AJAX requests). In terms of your settings getting wiped, that's odd... How are you reloading the extension? I just use [this application](https://chrome.google.com/webstore/detail/chrome-apps-extensions-de/ohmmkhmmmpcnpikjeljgnaoabkaalbgc?hl=en) for reloading the extension and everything works perfectly.

**Comment by FooSoft** [comment]
Closing dead issues

**Comment by gajewsk2** [comment]
I wasn't able to figure out a great ux for this, and my after considering my use-case it seems like #54 would be better for finding cards to fail in the anki interface.
