### ISSUE TITLE
ずる サ行変格活用 verbs (code "vz") aren't deinflected properly (論ずる、報ずる、信ずる、…)

### ISSUE THREAD

**Issue by epistularum** [FooSoft/yomichan#910]
Yomichan seems to fail to recognize some conjugations of ずる verbs (code vz)

In this series of conjugations:
論じない 論ぜぬ 論ざれる 論じます 論ずる 論ずれば 論じろ 論ぜよ

Apart from 論ずる itself, 論ずる doesn't appear anywhere in the result list.
I believe is has something to do with deinflect.json as I don't see any key for "ぜぬ" "ざれる" "ぜよ"

For reference:
https://www.kokugobunpou.com/%E7%94%A8%E8%A8%80/%E5%8B%95%E8%A9%9E-7-%E3%82%AB%E8%A1%8C%E5%A4%89%E6%A0%BC%E6%B4%BB%E7%94%A8-%E3%82%B5%E8%A1%8C%E5%A4%89%E6%A0%BC%E6%B4%BB%E7%94%A8/#gsc.tab=0
https://detail.chiebukuro.yahoo.co.jp/qa/question_detail/q10101971285

**Comment by toasted-nutbread** [comment]
You're probably right that zuru verbs aren't handled by the deinflector, but I think this is also a problem with the dictionary format. Taking jmdict_english as the example, it has the following entry for `論ずる`:
```jsonc
[
  "論ずる",      // expression
  "ろんずる",    // reading
  "vz vt",      // definitionTags
  "",           // rules
  713,          // score
  [             // glossary
    "to discuss",
    "to talk about",
    "to deal with (a topic)"
  ],
  1561640,      // sequence
  "P ichi news" // termTags
],
```

Note that the `rules` entry is empty, and in order for it to be used with deinflection, it would need to contain a verb type. In this case, it would probably need to be `'vz'`. Since this dictionary info was probably created using [yomichan-import](https://foosoft.net/projects/yomichan-import/), @FooSoft: do you think supporting -zuru requires a change to that?

Yomichan's deinflector currently uses `'v1', 'v5', 'vs', 'vk', 'adj-i'`, and if I am understanding correctly, may need to be expanded to include a `'vz'`.

Some references for my testing purposes:
* https://www.japandict.com/lists/vz
* http://jgrammar.life.coocan.jp/grammar/jgr_vcon.htm

**Comment by FooSoft** [comment]
Very interesting, will have to check the JMDICT source dictionary data. If it is there, then it is an importer bug.

**Comment by toasted-nutbread** [comment]
Friendly reminder @FooSoft, if you find an opportunity to look into this and fix the issue (assuming it is one), that may be a good time to update the Yomichan dictionaries available on the site. (#834)

**Comment by toasted-nutbread** [comment]
Is 論ざれる the correct form for presumably "passive"? I've found some references that list -じられる and -ぜられる, but didn't see any ざれる endings.

* http://jgrammar.life.coocan.jp/grammar/jgr_vcon.htm
* https://en.wiktionary.org/wiki/Appendix:Japanese_verbs

**Comment by toasted-nutbread** [comment]
New deinflections added in #1019; I will leave this issue open until I get around to updating the dictionaries with the new format (#834), which I'll try to do for the release at the end of the year.

**Comment by Thermospore** [comment]
> New deinflections added in #1019;

Just a heads up, I think https://github.com/FooSoft/yomichan/issues/1019 is a typo @toasted-nutbread 

Also, cool! I'll have to recompile jmdict and give this a try

**Comment by toasted-nutbread** [comment]
Correct, it was. I'll also be looking into recompiling dictionaries at the end of the year, and hopefully replacing the existing ones with the new ones.

**Comment by FooSoft** [comment]
All of the dictionaries have been recompiled; I've also created a script in the current development branch of yomichan-import to automate this in the future.

**Comment by Thermospore** [comment]
Just compiled the latest JMdict build with the latest Yomichan Import build and can confirm this conjugation is working for me 👍

**Comment by FooSoft** [comment]
You should be able to just use the pre-built dictionaries now, they have all been updated :+1:

**Comment by shoui520** [comment]
論ざれる still doesn't work, you can find more details here:

https://www.weblio.jp/content/%E8%AB%96%E3%81%96%E3%82%8C%E3%82%8B

**Comment by toasted-nutbread** [comment]
It looks like it's for what Yomichan considers the `potential or passive` rule? Correct me if I'm wrong on that. #1367
