### ISSUE TITLE
How do I actually even use this with the new update?

### ISSUE THREAD

**Issue by vladz0r** [FooSoft/yomichan#919]
So Yomichan just updated and nuked my setting.
I had it set to automatically lookup when mousing over things with no key modifier.
It turned into this and just doesn't work now. Been playing with it and asking around for half an hour.
![vYekWXc](https://user-images.githubusercontent.com/9376306/96049462-0c317700-0e46-11eb-96f3-beb512124455.png)

*edit*
For anyone wondering, this update probably killed your dictionaries like mine got killed.

**Comment by toasted-nutbread** [comment]
Those values should be correct for scanning without requiring any key to be pressed. Can you export your entire settings as it currently is?

Also, settings and particularly dictionaries should not have been wiped out, so I am not sure why that would happen.

**Comment by vladz0r** [comment]
Every few months, an update was killing Yomichan across all of my devices. I think this was due to not having Persistent Storage enabled. I might've not enabled it when I imported my settings onto this computer recently. My dictionaries were disabled and couldn't be reenabled by checking the boxes, so I had to remove and reinstall them. It just stopped working in the middle of reading yesterday night.

**Comment by toasted-nutbread** [comment]
> How do I actually even use this with the new update?

Apologies for the updated UI which may be confusing; I should have added a better description for how it's supposed to work. For now, I'm working on adding a simplified version of the UI which looks how it used to look. I'm working on a patch release which should hopefully be done today.

> My dictionaries were disabled and couldn't be reenabled by checking the boxes, so I had to remove and reinstall them.

That is probably a bug and I think I know why it was happening, I'll try to fix that quickly.

> I think this was due to not having Persistent Storage option enabled.

It is very annoying that this even needs to be done and browsers will just delete the data, even though the extension requests unlimited storage. This has been somewhat of a long-standing fight against browsers just deleting stored data.

With regards to not being able to scan, is/was that due to your dictionaries being disabled (or unable to be enabled) or being wiped out?

**Comment by vladz0r** [comment]
Not entirely sure because I was having both issues at once. It's working now. I had to reset the dictionaries and the hotkey settings to at least isolate the issue by getting it to work with the default shift-key setting.

**Comment by toasted-nutbread** [comment]
Cool, hopefully nothing else breaks until we get the patch release out.

I've created two changes addressing your feedback:
* #921 to include the simplified UI for scanning inputs (when advanced options are not enabled).
* #922 fixes the issue where you couldn't enable your dictionaries.

Thanks for the feedback
